### ISSUE TITLE
Prototype adding support for jQuery Mobile

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#137]
Just discussed this with @rxaviers - instead of doing tiny refactorings like the one in #102, we need to prototype how jQuery Mobile could use this tool to as their download builder as well.

The idea here is to just create a branch and hack support for creating jQuery Mobile downloads into it. Change the config.json file to contain their release (stable is currently 1.3), figure out a simple way to replace the manifest files as input with their AMD dependency tree. Either by generating manifest files based on that, or just replacing the code that reads the manifest files. Also need to figure out how to create a separate theme file, so that users can use jQuery Mobile's separate ThemeRoller for now.

References:
- Mobile download builder frontend: https://github.com/jquery/jquery-mobile-builder
- Mobile backend: https://github.com/gseguin/node-amd-builder

**Comment by Krinkle** [comment]
Closing in favour of https://github.com/jquery/themeroller.jquerymobile.com and https://github.com/jquery/node-amd-builder.
