### ISSUE TITLE
Link to this issue tracker on /download and /themeroller

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#138]
So people know where to report issues.

**Comment by arthurvr** [comment]
Can this be closed in favor of https://github.com/jquery/jquery-wp-content/issues/279? It's something that needs to be handled there.

**Comment by scottgonzalez** [comment]
This will need to be handled separately because the content is imported into jqueryui.com, but the repo to report bugs against is download.jqueryui.com.
