### ISSUE TITLE
Refactor `grunt prepare`: cache, tmp, jquery-ui

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#194]
Refactor `grunt prepare` to:

1) Cache: `./cache` (run once)
- Git fetch;
- Npm install;

2) Temporary working copy `./tmp` (deleted on each iteration).
- Npm prune && npm update; (usually quicker than the brand new npm install)
- Build manifests;

3) Local prepared copy `./jquery-ui/<version>`.

**Comment by jzaefferer** [comment]
We should revisit this after 1.12, with support for jQuery Mobile in mind.

**Comment by rxaviers** [comment]
Today, untracked leftover files of api.jqueryui.com (from different iterations) caused problems building 1-9 documentation. This needs to be fixed.

**Comment by Krinkle** [comment]
Partly done with https://github.com/jquery/download.jqueryui.com/commit/adf864f40a45dcdc8ef8cbbfe4e905b3600d53ea (https://github.com/jquery/download.jqueryui.com/issues/193). Not sure how this relates to api.jqueryui.com which is a WordPress site, but afaik this is working "good enough" today. Declining as feature task for now.
