### ISSUE TITLE
Improve banner.js test to use a more legitimate authors.txt

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#254]
On https://github.com/jquery/download.jqueryui.com/pull/247, @scottgonzalez said the below referencing https://github.com/jquery/download.jqueryui.com/blob/8fb518e480dcd0919cac99b667c65360b15b53d8/test/banner.js#L28.

> I know this is just a test, but I'd really like authors.txt to change to something at least looks legitimate.

**Comment by rxaviers** [comment]
@scottgonzalez, do you mean we should use a string similar to "jQuery Foundation and other contributors" instead of "authors.txt"?

**Comment by scottgonzalez** [comment]
exactly

**Comment by rxaviers** [comment]
Ok thanks
