### ISSUE TITLE
Need the ability to mark a module as hidden

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/download.jqueryui.com#265]
In mobile we have some non-trivial modules which are not really useful in and of themselves. They really shouldn't appear in download builder.

One implication of having such a feature though is that, if you select a top-level module that depends on some hidden modules, you end up selecting the hidden modules as well - obviously, but when you then de-select the same toplevel module, you now need to automatically deselect all its hidden dependencies as well, because the user does not have the ability to turn off those dependencies, because they're hidden.

**Comment by scottgonzalez** [comment]
The dependency part shouldn't require any changes at all. It's just a matter of not showing certain items in the UI.

**Comment by jzaefferer** [comment]
For jQuery UI this is working by not including any manifests (`//>>label:` etc.) in to-be-hidden modules.

**Comment by jzaefferer** [comment]
@arschmitz is removing manifest comments an acceptable solution to hide modules?

**Comment by arschmitz** [comment]
@jzaefferer yes

**Comment by jzaefferer** [comment]
That works. There are more tickets for support jQuery Mobile, I don't think we need to keep this one around.
