### ISSUE TITLE
https://jqueryui.com/download/ includes resources by HTTP

### ISSUE THREAD

**Issue by cobexer** [jquery/download.jqueryui.com#266]
AFAICT scripts from both download.jqueryui.com and code.jquery.com are apparently included using HTTP instead of either HTTPS or protocol relative URLs.

I poked around a little but couldn't find the relevant code here, thus no pull request with a fix =/

**Comment by jzaefferer** [comment]
Fixed by https://github.com/jquery/download.jqueryui.com/commit/f2750a71604125c98c28ca36c9998f3ec7818c0b
