### ISSUE TITLE
Fix regexp for deducing UI dependencies

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#271]
#### Issue

@jzaefferer has tested DB and found out:

> The clientside dependencies are broken, for example, while everything is unchecked, checking accordion or autocomplete won't check their dependencies. Their `data-dependencies` attribute has no value.

#### Background

jQuery UI had its manifest files removed, then DB started deducing the dependencies by parsing the AMD header of its source files. See #243 for more information. This was implemented by PR #244.

After PR #244 has landed, jQuery UI had coding style changes (e.g., https://github.com/jquery/jquery-ui/commit/fac517ebb973396292e6f96fc1bda6888dc3da10), which broke the #244 [regexp](https://github.com/jquery/download.jqueryui.com/blob/d77ffffcdc027edccaaf91e3e3cdcedd732cb463/lib/jquery-ui-1-12.js#L71-L74).

#### Solution ideas

Today, jQuery UI has both styles living together (e.g., [accordion](https://github.com/jquery/jquery-ui/blob/b240eed81b96c9c4128ca5682d876fbc6f96a9c4/ui/accordion.js#L23-L27) uses the new style, [button](https://github.com/jquery/jquery-ui/blob/12df1b7dad135aa57640be631277db3f7d75d672/ui/button.js#L23-L27) uses the older one). One approach would be to update the regexp to be more lenient and allow both forms. Another solution would be to update jQuery UI to be consistent using the newer style on all of its widgets. A third and better solution would be to have DB to parse the UI files using AST trees (for example, by using https://github.com/jquery/esprima) and avoid style issues on its regexps.

- [ ] Include `Ref #243` in the fix commit.

**Comment by arschmitz** [comment]
@rxaviers all widgets are updated you just need to wait for button to land thats the only reason its not updated was to prevent conflicts when button merges

**Comment by scottgonzalez** [comment]
For now, I'd say just update the regex since it's a small change. Eventually moving to an AST sounds like the right approach though.

**Comment by rxaviers** [comment]
Fixed this by using "a more lenient regexp to allow both style forms".
