### ISSUE TITLE
1.9.2 download sets theme scope to "css"

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/download.jqueryui.com#275]
Reported via Twitter: https://twitter.com/japerr/status/656848592125095939

**Comment by jzaefferer** [comment]
I can't reproduce this. It uses the specified scope, I can't get it to output "css" unless that's what I input.

**Comment by scottgonzalez** [comment]
Confirmed this is fixed. It was definitely broken when that user reported the error though.
