### ISSUE TITLE
Replace bower dependencies with npm modules

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#279]
eventemitter, handlebars and lzma are available on npm. farbtastic is on GitHub ( https://github.com/mattfarina/farbtastic ), with a package.json, though apparently the 1.3u release wasn't published to npm. Could either install from git, publish that ourselves, ask the author to publish the old release, or switch to the 2.0 release (currently only in alpha).

**Comment by jzaefferer** [comment]
Both handlebars and lzma are dependencies in package.json already.

**Comment by Krinkle** [comment]
Mostly done by @mgol in 2020 with https://github.com/jquery/download.jqueryui.com/commit/2c1990526c0cd4901c9bc3169 as part of https://github.com/jquery/download.jqueryui.com/pull/552. The rest are fine as-is given the project is frozen. The checked-in dependencies are stable and arguably even more stable than npm would be.
