### ISSUE TITLE
Support 1.12 release script

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#282]
jQuery UI 1.12 runs this during the release: https://github.com/jquery/jquery-ui/blob/9644e7bae9116edaf8d37c5b38cb32b892f10ff6/build/release.js#L37-L55

Testing with:
```
node release.js --pre-release=1.12.0-beta --remote=jzaefferer/jquery-ui
```
I eventually get this error:
```
/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/jquery-ui-files.js:76
		if ( !minified[ file.path ] || options.skipCache ) {
		              ^
TypeError: Cannot read property 'ui/data.js' of undefined
    at Object.JqueryUiFiles.min (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/jquery-ui-files.js:76:17)
    at Builder_1_11_0.min (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder-1-11.js:99:17)
    at Array.map (native)
    at Array._.extend.map (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/files.js:24:37)
    at Builder_1_11_0 (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder-1-11.js:119:5)
    at Object.Builder.build (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/builder.js:59:31)
    at _build (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/lib/themes-packer.js:53:12)
    at /Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:486:21
    at /Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:185:13
    at iterate (/Users/jzaefferer/dev/jquery/jquery-release/__release/repo/node_modules/download.jqueryui.com/node_modules/async/lib/async.js:108:13)
```
In builder.js, there's nothing specific to 1.12: https://github.com/jquery/download.jqueryui.com/blob/master/lib/builder.js#L58-L62

**Comment by jzaefferer** [comment]
Somewhat related, this requires a packer-1-12 module which doesn't exist: https://github.com/jquery/download.jqueryui.com/blob/3d2db8ab700a7159ab2a463cbbdf29fc5dbc15ae/lib/packer.js#L33

**Comment by rxaviers** [comment]
Hi @jzaefferer, the release script must be updated according to https://github.com/jquery/download.jqueryui.com/commit/eda7d35b545950e14c5cb9073b9c98df460ee201#diff-dc64f35b02398a7d4cfe87e136074600L104. Basically, jQuery UI 1.12 is supported by
https://github.com/jquery/download.jqueryui.com/blob/eda7d35b545950e14c5cb9073b9c98df460ee201/download.js#L145-L169.

**Comment by jzaefferer** [comment]
This is what I've come up with based on that, which manages to produce a zero byte zip file: https://gist.github.com/jzaefferer/6e1999993ac74fa42437

Here's the full file, along with a file for testing it (outside of the full release script), just need to install the npm dependencies manually: https://gist.github.com/jzaefferer/f219a9b440b3ef218698

This surely doesn't work since I'm not passing any theme vars, and as far as I can tell, those are required. I don't know where to get them from.

In addition, the zip package is supposed to contain ALL themes, not just a specific one. That seems unsupported with this approach. I don't even know where to begin to address that.

**Comment by rxaviers** [comment]
Please, check your `components`. Follow a working example that is similar to yours: https://gist.github.com/rxaviers/5927c291f2cf33e7ed96.

> This surely doesn't work since I'm not passing any theme vars, and as far as I can tell, those are required. I don't know where to get them from.

You don't need to pass theme vars (demonstrated by the above gist). But, theme vars can be obtained at https://github.com/jquery/download.jqueryui.com/blob/master/lib/themeroller-themegallery.js.

> In addition, the zip package is supposed to contain ALL themes, not just a specific one. That seems unsupported with this approach. I don't even know where to begin to address that.

The package that handles building this file is this one: https://github.com/jquery/download.jqueryui.com/blob/master/lib/themes-packer.js. Although, I think this should be part of the release script, not DB. Also this should be updated to use the new packager (like 1.12).

Please, just let me know in any further questions.

**Comment by jzaefferer** [comment]
I can't use this in the release script:
```js
var jqueryUi = JqueryUi.find( "1.12.0-pre" );
```
This used to work:
```js
var jqueryUi = new JqueryUi( path.resolve( "." ) );
```
That's the only difference I can spot now, I'm not sure if that's the problem though. I still get a zero byte zip file when running the (modified) release script. Running your gist inside DB works fine.

I'll push what I have to the jquery-ui repo.

**Comment by jzaefferer** [comment]
@rxaviers can you take a look at https://github.com/jquery/jquery-ui/pull/1642 and try to run `node build/release-test.js`? After npm-installing the three dependencies.

**Comment by jzaefferer** [comment]
PS: The test script now installs dependencies if not present, yet.

**Comment by rxaviers** [comment]
For the record, @jzaefferer and I chatted today. The remaining thing was porting the themes package to use the new node-packager. Work has been started here https://github.com/jquery/download.jqueryui.com/tree/package-1-12-themes.

**Comment by jzaefferer** [comment]
@scottgonzalez can you help test this? 

Check out https://github.com/jquery/download.jqueryui.com/pull/286 and run `npm link`
Check out https://github.com/jquery/jquery-ui/pull/1642 and run `npm link download.jqueryui.com`, then `node build/release-test.js`

**Comment by jzaefferer** [comment]
Updated to DB 2.1.2 and merged to master.
