### ISSUE TITLE
Local ThemeRoller setup help.

### ISSUE THREAD

**Issue by nb-user** [jquery/download.jqueryui.com#284]
Hi, I am trying to run themeroller code locally. So far I have downloaded most recent version (2.1.1) on my Ubuntu VM and can get to ThemeRoller. I have installed, all required dependencies mentioned in ReadMe file. I am able to successfully install and run ThemeRoller section of the application but having some trouble to get Download running. Even downloading existing theme times out. Any idea what could be wrong? May be I am missing some deployment/required permission set. Can anyone please help?

You can check my deployment [here](http://tn-ubuntu.cloudapp.net/themeroller)

Thanks

**Comment by rxaviers** [comment]
Hi, do you get any backend errors (in `/var/log/syslog` or console if using `--console`)?

**Comment by nb-user** [comment]
First of all thanks for responding to my query.
Yesterday I had some progress on debugging the DownloadBuilder source code.
What I have found out is that I could get download working for ​1.12​.0-pre
themes​ out of the box​. But any other ​stable or ​legacy theme downloads
are failing and giving following error. It looks like, soon to be
deprecated builder and packer are having some issues. I get ​following
error when I am trying to download ​1.9.2, ​1.10​.4​ theme​s​. ​For ​1.11.4
​theme I don't get any ​error on console​, request just times out. Syslog
doesn't report any suspicious activity in log. I have copied the contents
of syslog in this email. If you need any further details about the app
deployment, please let me know.

Since this is my first attempt to look at full blown enterprise level
application, I am using my own method for debugging. Like
debugger.log(message) to console​ for finding out sequence of execution.

*****Errors reported to console while downloading theme 1.9.2 and
1.10.4*****
User request exception: TypeError: ext must be a string
    at posix.basename (path.js:550:11)
    at Array.map (native)
    at Array._.extend.map (/var/www/download.jqueryui.com/lib/files.js:24:37
)
    at Builder_1_10_0 (/var/www/
download.jqueryui.com/lib/builder-1-10.js:72:53)
    at Object.Builder.build (/var/www/
download.jqueryui.com/lib/builder.js:61:31)
    at _build (/var/www/download.jqueryui.com/lib/packer-1-10.js:50:11)
    at /var/www/download.jqueryui.com/node_modules/async/lib/async.js:486:21
    at /var/www/download.jqueryui.com/node_modules/async/lib/async.js:185:13
    at iterate (/var/www/
download.jqueryui.com/node_modules/async/lib/async.js:108:13)
    at async.forEachSeries (/var/www/
download.jqueryui.com/node_modules/async/lib/async.js:124:9)

*****Syslog*****
Nov 10 06:56:51 tn-ubuntu rsyslogd: [origin software="rsyslogd"
swVersion="5.8.6" x-pid="1054" x-info="http://www.rsyslog.com"] rsyslogd
was HUPed
Nov 10 07:17:01 tn-ubuntu CRON[49931]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 08:17:01 tn-ubuntu CRON[50538]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 09:17:01 tn-ubuntu CRON[51114]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 10:17:01 tn-ubuntu CRON[51211]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 11:17:01 tn-ubuntu CRON[51291]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 12:17:01 tn-ubuntu CRON[51433]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 13:17:01 tn-ubuntu CRON[51500]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)
Nov 10 14:17:01 tn-ubuntu CRON[51567]: (root) CMD (   cd / && run-parts
--report /etc/cron.hourly)

Also does nodemon works with this application? As of now on every single
update to any JS file, I have to restart the app. Also I can't get any
stylesheets ​or images loaded when I use forever to run the app. Any idea
how can I deploy this app as daemon service?

Again thanks for your help.

**Comment by rxaviers** [comment]
All I can say is that I ran into the same issue as you did. I don't have available time to dig in for now (or in foreseeable future), but I suspect it has to do with the node version.

I've created a brand new clone and followed the [getting-started](https://github.com/jquery/download.jqueryui.com/#getting-started) instructions and had the same problems. I'm on Ubuntu 15.10, using Node.js `4.x`. I also tried using Node.js `0.12.7`, but then it fails with a different issue:

    Caught exception: /tmp/download.jqueryui.com/node_modules/connect/node_modules/qs/lib/index.js:5
    const Stringify = require('./stringify');
    ^^^^^
    SyntaxError: Use of const in strict mode.

I've marked this issue as a bug.

**Comment by nb-user** [comment]
Here is a little update on on download ​of 1.9.2, ​1.10​.4​ theme​s. It
looks like on line#72 of of /lib/builder-1.10.js, path.basename is called
using map function.

banner( jqueryUi.pkg, files.i18nFiles.paths().map( path.basename ) ) )

On this line for some reason 3 different arguments(element of array, index
of element and array element) are passed out of map function to
path.basename. Second argument is index of array element which is integer
value. Thats where exception is thrown. I believe same is the case with
/lib/builder-1-11.js
For now I have overridden the functionality of path.basename
in corresponding 2 JS files, so that only array of filenames will be passed
further down. This has helped and I can download above 2 different types of
theme. Still need to debug what's wrong going on with ​1.11.4 ​theme
download. Hope this helps for further debugging.

Thanks

**Comment by mgol** [comment]
Download Builder & Themeroller were updated to work on newer Node.js versions in PR #552 and the issue mentioned here was fixed as part of that. Closing.
