### ISSUE TITLE
Cannot download bundle

### ISSUE THREAD

**Issue by idkw** [jquery/download.jqueryui.com#287]
Hello

When I go to the download page without changing any checkbox and clicking on download I get the following message :

http://jqueryui.com/download/#!

```
Ooops!!!

An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact us if the problem persists.
```

Thank you

**Comment by marknl** [comment]
same here.

**Comment by rxaviers** [comment]
@idkw and @marknl thanks for reporting. We had a bad deploy. But, it should be fixed by now. Please, just let we know if you encounter any other problems.
