### ISSUE TITLE
Unable to download 1.12.0-beta.1 of jQuery UI

### ISSUE THREAD

**Issue by andreasrosdal** [jquery/download.jqueryui.com#289]
Downloading version 1.12.0-beta.1 of jQuery UI doesn't work from here: https://jqueryui.com/download/

I would like to try out jQuery UI 1.12.0-beta.1 with the humanity theme. How can I do that?

**Comment by scottgonzalez** [comment]
Download builder is not configured to work over HTTPS yet, please use HTTP.
