### ISSUE TITLE
Can't download Vader Theme for version 1.12.0-beta.1

### ISSUE THREAD

**Issue by tward392** [jquery/download.jqueryui.com#292]
Get the following:

File not found

Firefox can't find the file at http://download.jqueryui.com/download.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.

when I pick Vader in the drop-down and click download and version 1.12.0-beta.1 (Beta, for jQuery1.7+)

**Comment by scottgonzalez** [comment]
Confirmed. Interestingly, this is only a problem with Vader; every other theme works fine, and Vader works with 1.11.4.

I'm now getting Bad Gateway responses, so there's likely a larger issue at play.

**Comment by scottgonzalez** [comment]
See also #291.

**Comment by scottgonzalez** [comment]
This is still a problem with 1.12.0.

**Comment by scottgonzalez** [comment]
I think this may be caused by https://github.com/jquery/download.jqueryui.com/blob/1f081451560d65d5757b8e9bba0e0e101d8dbaa6/lib/themeroller-themegallery.js#L1220 having an extraneous "tr&" in front of the name. I'm not sure if the `cachedZThemeParams` property is correct though.

@rxaviers how can we check `cachedZThemeParams`?

**Comment by rxaviers** [comment]
You can code or decode by using zparams.js available in the project.

By fixing the extraneous "tr&" (in green), the zparams is different than what we have (in red):

```diff
- 5d00000100da04000000000000003d888a876183007269df494da9b9c0c3aec70be95feff3605b597b797cf801619b97f2e64b1b6399de9737af85fe32e0828278bd24e77c4a074f564a82fada981d575dbec5f2b870019edd0d79683ad2242b13794f178310bda907557c1c5f8549059576a79e7fee80ac7511ee3cefa601ce3045e17be12f96a19b9205cfeb6dac7dcbb5c9dd66171b35eb319586ec0525f6d09bf0937eab106fec46d3171c72a0cf739832e91f52e3d59409a8103a62bf763a666289994fe5bd3c498ed11d7f495ae689569894bfc08aed801713f890d4107ac8cf06da5bf29736db25268d26df8fb856323612c2a7baf92535e0fa6184118d5e476e36baf78e07d602e886b5d41ec4dcd8d8d75d6c5f033bcd11841c16cbea107026825a0f92918048ceeda5014c107401d62590dcd0f58a9a76616961c0918098c39e070a77ef72c78d17fb0a8e3e2c50d1ca2777302fae34df28efae6dc43e2cf9fc382ddd0b7728fb0f6cb2ad26c31477bb5098a0c1fe613f7b80c486d8a3308c1bae6c148af0de6ac138627951fc9bffffb5851f58
+ 5d00000100e604000000000000003d8889c65436c3174fe4e7e9506abc2c9b9a5e07eb3c69e54a609cc8d72aebf38669a452e2f6507c2610c92ac54ad807433260455e76aac2f0e9b275ec9f4ee1de7e0cb5220b1c6159ffe3b39c26972180390a32e2cb6d9501c0ba6342843ead419fec4931c38d356492337481a0f64f6a1e7307ccd124b2094cc3de3b65869ebe83754995a518a53ee3a6b119c1533e5550eea0f0563341fb089967edb1871f03c117bb94d6f49168f8b2ff0ff588bb8446ebad76ec6e6cbf1329c2564c336c51fd73de41d399e61fa3fe684948202bb57287ce2bc385148564f68f1fc89b849acb2eadcb228fc4aafa2840f6805aaff0a55d547cb9f88156988d4e372d3d1932bf8c6558148e017ad13c697ade7cc3833cf0e18536cfd655309a3f674aa36ccecbb4c004bc535e0be848c406ce9fd2b0bc1d182e4fff19e9ab0cafa8069f7e33fcf2ce18adbde8e54310e604231a9165ca68abc9019fe5fd2cd047f442eeddcd09a47bd8be6f8327995a088c64bfb6523cfcf481a78a01a3cea8e889d12ced696a6722a8196675744d903ffff5098ce6
```

---

Useful link:
- https://github.com/jquery/download.jqueryui.com/blob/master/lib/themeroller.js#L362-L364

Useful test code:

```
$ node
> var zparams = require('./zparams');
> var varsObject = {...} // theme vars
> zparams.zip(varsObject, console.log);
<output>
```

**Comment by rxaviers** [comment]
Edit: I made some minor edits in the previous comment. Please refresh.
