### ISSUE TITLE
I cant download a custom package 

### ISSUE THREAD

**Issue by evwebcoder** [jquery/download.jqueryui.com#293]
I can't download a custom package, this is the first time I see this issue.

I am just downloading a 1.11.4 version and then I toggle all to unselect everything and select the following ones:
• spinner
• tooltip
• datepicker

After I click download, I can re-directed to this page with a 502 error message.

**Comment by evwebcoder** [comment]
Actually I was able to download the file on Safari, wired. 

I was initially was using Chrome, which it still doesn't work. At least I got the file I needed using Safari.

**Comment by scottgonzalez** [comment]
Are you still getting 502s or is the service working properly for you now?

**Comment by shyam1joshi** [comment]
Me too .. cant download custom package at all

**Comment by scottgonzalez** [comment]
*Please* provide more information. What settings are you changing? What URL are you on when the download fails?

**Comment by shyam1joshi** [comment]
well about an hour ago i kept getting 502 response , now if i deselect datepicker and dialog with package 1.10.04 , it starts downloading and then stops .. the last one i am trying just now seems to be downloading properly. But even then speed for download seems horrible about 3.5 kbps , I am hoping this one completes

**Comment by scottgonzalez** [comment]
Where are you located?

**Comment by scottgonzalez** [comment]
cc @jquery/infrastructure

**Comment by shyam1joshi** [comment]
I am located in India , looks like the cloudflare routers thru mumbai server , but the download has completed so i am good at this point .. Thanks ..

**Comment by shyam1joshi** [comment]
BTW URL i used http://download.jqueryui.com/download

**Comment by aulvi** [comment]
Hello @shyam1joshi! Sorry about that, I restarted the service and we're back online. Thanks for the heads-up!

**Comment by shyam1joshi** [comment]
No problem , just glad , i could help , thanks to you awesome guys , we lowly developers can make things work ..  cheers ...

**Comment by nmschulte** [comment]
I'm receiving 502 Bad Gateway errors from CloudFlare.  I am trying a custom build of 1.11.4 w/ Draggable+Droppable+Sortable (https://jqueryui.com/download/#!version=1.11.4&components=1110110010000000000000000000000000000), and the "Download" link takes me to the 502 error page: http://download.jqueryui.com/download

@aulvi need to restart the service again?

**Comment by nmschulte** [comment]
It's working again.  Thanks.  :)
