### ISSUE TITLE
Cannot modify themeroller

### ISSUE THREAD

**Issue by SparksinTexas** [jquery/download.jqueryui.com#297]
http://jqueryui.com/themeroller/#themeGallery

Normally on the left side is a box containing all the different options such as tab color, background color, etc.  That is not opening.  I also cannot access the gallery.

I have been trying for over 24 hours.  I have used both chrome and Internet Explorer.  I am in Texas USA.

<img width="476" alt="capture" src="https://cloud.githubusercontent.com/assets/18615402/14742264/cb20fdd4-0860-11e6-9516-5cfb8dc95709.PNG">

**Comment by scottgonzalez** [comment]
I'm not seeing any problems. Do you get any errors in your console?

**Comment by SparksinTexas** [comment]
Sorry, not sure what console you mean.  I am a talented user who can change code only if someone tells me which line to modify.

It was working night before last and then it just stopped.  Themeroller isn't playing nice with my themes colors so I had to keep going back and forth trying to get theme modified so I could actually see my tags.  Then between one attempt and the next the themeroller website stopped working for me.

Regrettably, I'm not going to be able to look at it again until tonight because I have to get to work.

<img width="309" alt="capture" src="https://cloud.githubusercontent.com/assets/18615402/14742838/d8d8f460-0863-11e6-84db-8dd678b727a6.PNG">

**Comment by scottgonzalez** [comment]
In Chrome:

* Open the developer tools with View -> Developer -> Developer Tools.
* Click the Network tab, check the "Disable cache" option.
* Click the Console tab.
* Reload the page.
* See if any errors show up in the console.
