### ISSUE TITLE
1.12.0-RC2 themes: bad build

### ISSUE THREAD

**Issue by sebfz1** [jquery/download.jqueryui.com#298]
Hi,

Obviously the themes built for `1.12.0-rc2` are wrong: `jquery-ui.css` files are around 17k whereas there should be > 35k. I guess it actually only contains theme.css...

http://jqueryui.com/resources/download/jquery-ui-themes-1.12.0-rc.2.zip

Thanks in advance,
Sebastien

**Comment by sebfz1** [comment]
Hi,

Any update on this?

Thanks in advance,
Sebastien.

**Comment by scottgonzalez** [comment]
We're not sure what caused all of the pre-release theme zips to be wrong, but as a temporary fix you can just download the themes from http://jqueryui.com/download/. We'll make sure this is working properly before the 1.12.0 release.

**Comment by scottgonzalez** [comment]
This is caused by https://github.com/jquery/download.jqueryui.com/blob/5abaf636320b85986c7cfa875f3b896dd76f514e/Gruntfile.js#L385-L388 which seems to only exist because the theme packager builds on top of the standard packager. I'm working on making that not the case so that conditional logic can go away.

**Comment by sebfz1** [comment]
Thanks Scott! Any date for rc3?

**Comment by scottgonzalez** [comment]
No, but I'm working on updating the RC 2 zip. I probably won't update the other pre-release zips because download builder isn't designed to generate old pre-release files.

**Comment by scottgonzalez** [comment]
For some reason the production site is not serving the updated zip. We're still debugging that, but in the meantime you can download the zip straight from the source: https://github.com/jquery/jqueryui.com/blob/master/resources/download/jquery-ui-themes-1.12.0-rc.2.zip

**Comment by sebfz1** [comment]
Great, thanks Scott! :)

**Comment by scottgonzalez** [comment]
Just following up to note that the site now has the correct themes zip.
