### ISSUE TITLE
HTTPS custom download does not show Themeroller options

### ISSUE THREAD

**Issue by tucson-tom** [jquery/download.jqueryui.com#299]
https://jqueryui.com/download/

It took me a while to figure out why the Themeroller options do not show.  Using HTTPS causes a CORS violation.  Switching to:

http://jqueryui.com/download/

Appears to work fine.  I came into jQuery UI off of a Google Search, which drops in on a HTTPS URL if the server supports HTTPS.

**Comment by scottgonzalez** [comment]
We have full support for HTTPS now.
