### ISSUE TITLE
When i downloading custom components i found 502 error

### ISSUE THREAD

**Issue by vishalkakadiya** [jquery/download.jqueryui.com#301]
I am downloading jquery UI library with my custom requirements. I found 502 error. 
Check screenshot here https://nimbus.everhelper.me/client/notes/share/465883/bt3kfsd5pxrqfxau1duv

But after sometime it will be ok for downloading.

**Comment by scottgonzalez** [comment]
Unfortunately there's nothing we can do about this. We're having intermittent problems with our host and it's affecting all of the foundation's sites.
