### ISSUE TITLE
Error 502  - Bad Gateway when Downloading Themeroller

### ISSUE THREAD

**Issue by bilcker** [jquery/download.jqueryui.com#302]
when trying to download a them I get

Error 502 Ray ID: 2a92577802e923cc • 2016-05-26 15:43:15 UTC

Says 

download.jqueryui.com Host Error

**Comment by agenciahouse** [comment]
Error 502 Bad gateway

**Comment by innowintay** [comment]
Error 502 Ray ID: 2a92bd38734e0107 • 2016-05-26 16:52:43 UTC
The web server reported a bad gateway error.

**Comment by scottgonzalez** [comment]
I've locked this issue because all of the repeat comments are not helpful and will not enable us to resolve this any faster.

**Comment by arschmitz** [comment]
The issue has been resolved
