### ISSUE TITLE
Trouble with jquery ui download

### ISSUE THREAD

**Issue by gurdurix** [jquery/download.jqueryui.com#307]
![image](https://cloud.githubusercontent.com/assets/7022661/16735406/ed5b348e-4756-11e6-83e1-d0036cf69b5d.png)

**Comment by stanecli** [comment]
same for me

**Comment by francotalarico** [comment]
Same, never start the download...

**Comment by gurdurix** [comment]
Actually, its works.

**Comment by jzaefferer** [comment]
Thanks for the reports! And thanks to whoever fixed the issue.

**Comment by monoregent** [comment]
Well @jzaefferer says that it's fixed, but i'm getting error 504

**Comment by jzaefferer** [comment]
Yeah, the issue isn't resolved yet. Please follow #306 for updates.
