### ISSUE TITLE
502 has now changed to 504

### ISSUE THREAD

**Issue by TCKay** [jquery/download.jqueryui.com#308]
I was seeing a 502 error and now it's changed to a 504.

https://www.dropbox.com/s/m10cw48t8kz4jai/Screenshot%202016-07-12%2011.39.27.png?dl=0

**Comment by grimtyr** [comment]
Same here, seems like the host is out of service, any mirror ?

**Comment by jzaefferer** [comment]
Closing in favor of #306, please follow that instead.
