### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by cristiammercado** [jquery/download.jqueryui.com#310]
Any solution to this problem? It's impossible to download a jQuery UI custom theme.

**Comment by seanhealy** [comment]
I seem to be seeing the issue in Safari but not in Chrome… Haven't tested other browsers.

Update Safari just came back to life. However for the lifetime of my seeing the issue there were no options under the `theme` title.

**Comment by cristiammercado** [comment]
It's incredible since 19 days ago someone reported the error and still the same. :( :(

**Comment by ValeriePintar** [comment]
I'm getting the error in Chrome but Firefox works, just FYI!

**Comment by aulvi** [comment]
@cristiammercado Please provide as much detail as you can about how you are customizing the theme. I cannot reproduce the error myself so I have to assume it's something specific to your requested build that is freaking the server out. Thanks!

**Comment by jzaefferer** [comment]
Should be resolved now. Use #313 for updates.

**Comment by hh-com** [comment]
When try to download only Selectmenu (1.11.4) the following errors come:
1) 502 (yesterday)
2) 504 (today)
3) Ooops!!!
An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact us if the problem persists. (today)
