### ISSUE TITLE
Gateway time-out. Error 504

### ISSUE THREAD

**Issue by gladisihor** [jquery/download.jqueryui.com#315]
I can't download any scripts during two last days. I need to download this combination: 
[http://jqueryui.com/download/#!version=1.12.0&components=111000000100100000000000010000000000000000000000]

**Comment by jzaefferer** [comment]
See #313

**Comment by gladisihor** [comment]
I downloaded jquery-ui-themes-1.12.0 archive but I didn't find any javascript files there. I didn't find any other solutions there...
