### ISSUE TITLE
Error 504. Gateway time-out.

### ISSUE THREAD

**Issue by gladisihor** [jquery/download.jqueryui.com#317]
I can't download any scripts during two last days. I need to download this combination: 
[http://jqueryui.com/download/#!version=1.12.0&components=111000000100100000000000010000000000000000000000].
Please do not send me to closed issue #313, because there are no any solution for my case:
I downloaded jquery-ui-themes-1.12.0 archive but I didn't find any javascript files there. I followed to links and didn't find any other solutions there...

**Comment by jzaefferer** [comment]
Please give us some time to address the known issues. Opening more tickets isn't helping.
