### ISSUE TITLE
Autocomplete jquery download builder goes on 504  timeout

### ISSUE THREAD

**Issue by unixforce** [jquery/download.jqueryui.com#318]
Hello, when I jave just selected only "autocomplete" plugin && download with jquery 1.12.0(Stable, for jQuery1.7+) server goes on timeout server 504. Anyone have same issue ??

**Comment by jzaefferer** [comment]
Duplicate of #313.  Please give us some time to address these known issues.

**Comment by unixforce** [comment]
Ok, thanks a lot in advance.
