### ISSUE TITLE
Vader theme "File Not Found" still occuring in Download Builder...

### ISSUE THREAD

**Issue by DarthGuybrush** [jquery/download.jqueryui.com#320]

**Comment by yourchoice** [comment]
![image](https://cloud.githubusercontent.com/assets/531720/16836287/80ebde54-49c5-11e6-87d9-04053d71e11b.png)

**Comment by jzaefferer** [comment]
Yes, we're aware of the issues, please follow #313 for updates. We don't need more reports.
