### ISSUE TITLE
504 download custom package

### ISSUE THREAD

**Issue by dGilli** [jquery/download.jqueryui.com#323]
I am having trouble downloading a custom package ending up in a 504 timeout.

Downloading:
- Effects Core
- Slide Effect

Version: 
1.12.0

Selection Link:
http://jqueryui.com/download/#!version=1.12.0&components=000000000000000000000000000000001000000000000010

**Comment by jaspermdegroot** [comment]
Closing as duplicate of https://github.com/jquery/download.jqueryui.com/issues/313
