### ISSUE TITLE
Timeout error when trying to download custom package

### ISSUE THREAD

**Issue by theabeing** [jquery/download.jqueryui.com#328]
tried three times to download this: http://jqueryui.com/download/#!version=1.12.0&components=111111111111000000000000001000000000000000000000

and got timeout error. 
Please note that under "Theme" there were no input elements visible

**Comment by vincelord** [comment]
same here. tried a few times these days without luck

**Comment by jaspermdegroot** [comment]
Closing as duplicate of https://github.com/jquery/download.jqueryui.com/issues/313
