### ISSUE TITLE
Custom Themeroller not updating

### ISSUE THREAD

**Issue by jjsibborn** [jquery/download.jqueryui.com#329]
I have accessed Themeroller from both google (https link) and manual link (http).  The Theme Roller page loads ok, but when I change an option it takes around 15seconds to refresh, screen returns to a default state (grey bars) and no changes are applied.
I have tried the site in IE (11), Chrome, Firefox.  All have the same problem.

Initial URL: http://jqueryui.com/themeroller

Changed URL after changing Clickable Active State and change to a different colour:
http://jqueryui.com/themeroller/#!zThemeParams=5d00000100d805000000000000003d8888d844329a8dfe02723de3e5700bbb34ecf36cdef1e1654faa0015427bdb9eb45ebe89aaede0ec5f0d92417fcc6551ce804ff46bf543167700d2cf4e583f2515147aacb86ffa11c0e588dae72a13c98dc37478199f7eea536e99705404149ad3e00bc8b1ab61d369a189b8543dfe7c6f3b8773513a278552790da0a3ff391cfa52421f68c6fa7223f7e87b0f0d8410077deb02c07796d7baf36e6281ad8154b7e79274ba2809c56dd4c8ced5a6a8ee71375703912c06842ac53fb1ef3d881a18eb5c5baf0baa2846e56310128ae8aba2371243b65b587628051295649d11b5f613f11b195ec15a2a936103927844f78bd2cc7cd74b6fd83180de3b93f2601920d6b91834b809748082194e7b0efbd251a2fa24377a3ba3440f3ef0312acce7d95e3069d0e2eb13b30a75da4fa35a4e564f1c8666bf30e983ef96e570323ae1f0ead223f4d3dcd986817e2b748a71cdb4e5bc9ee523530c4d969e2c3bbdbcb64d992509d166fe6ecb891c0b447d504a89ec56844cbf4a4be48766e3d019bb9ecbd3ce151e53da2d6e34b75773c64bbe4a01501bb3b3e599b78e947c54283aeade4a616fbcbba131aa11c0dfbdecd1690c1ca62c1f946d2a6d1ef870028472d8d79096909effe08a5f09

I have inspected the page and I am getting an error:
GET http://download.jqueryui.com/themeroller/parsetheme.css?ffDefault=Arial%2CH…pacityHover=&bgImgOpacityActive=&bgImgOpacityHighlight=&bgImgOpacityError=  jquery-1.11.3.js:5761 

I am not sure if this is linked to any of the other issues here.
![capture](https://cloud.githubusercontent.com/assets/20560752/17014577/1b4df76e-4f1d-11e6-8103-bd8d24f3759a.PNG)

**Comment by StevenLiekens** [comment]
Very much related to #313

**Comment by jjsibborn** [comment]
Thank you for that, I did read that chain before I posted, and it mentioned it had been possibly fixed, but also it was a download issue with a Gateway issue, where as I am not able to even generate a custom them, so was unsure if it was linked.
I will keep an eye on both.
Thanks again

**Comment by scottgonzalez** [comment]
Yeah, this is #313.
