### ISSUE TITLE
Base theme: when checkbox is checked no check icon appear

### ISSUE THREAD

**Issue by Tecnezio** [jquery/download.jqueryui.com#332]
As seen on jqueryui demo (https://jqueryui.com/checkboxradio/#default), using base theme, when a checkbox is checked, no icon seems appear.
Looking the css seems that the rule apply a white icon on a white background.

**Comment by scottgonzalez** [comment]
This has already been fixed and will be released in 1.12.1. In the future, please file bugs at https://bugs.jqueryui.com
