### ISSUE TITLE
Unable to download custom theme (jQuery UI - Server Error)

### ISSUE THREAD

**Issue by dantunes** [jquery/download.jqueryui.com#334]
Hi! I'm trying to download a custom theme for the 1.9.12 version but the server outputs the following message:

> jQuery UI - Server Error
> Ooops!!!
> An unexpected error seems to have occurred. Why not try refreshing your page? Or you can contact us if the problem persists. 

Also, I can't download the predefined themes, e.g. Smoothness theme. It shows me the same error.

Thanks! hope you can fix this issue.

Regards,
David

**Comment by scottgonzalez** [comment]
This is working fine for me. Are you still having problems?

**Comment by dantunes** [comment]
Thanks!, it is working for me now too. It could have been a temporary downtime, but now it is working as expected :)
