### ISSUE TITLE
jQuery UI 1.12.1 is not working for jQuery1.7

### ISSUE THREAD

**Issue by golodenko** [jquery/download.jqueryui.com#336]
jQuery UI 1.12.1 droppable is using **.addback()** that was added in 1.8 but claims to work with 1.7+.
http://jqueryui.com/download/

http://api.jquery.com/addback/
> version added: 1.8

**Comment by scottgonzalez** [comment]
I'm assuming you created a custom download since you're posting in download builder's issue tracker. Did you include the jQuery 1.7 Support module in your download?

**Comment by golodenko** [comment]
Oh, that was embarrassing. Thank you Scott.
