### ISSUE TITLE
Trouble Downloading Vader

### ISSUE THREAD

**Issue by NaheemAdio** [jquery/download.jqueryui.com#338]
Other themes are downloading just fine but when I select Vader I can't download it.

**Comment by Alpoy** [comment]
Still not working

**Comment by Thwipshot** [comment]
So what are we supposed to do then if we want to be able to use this theme but can't?  I just tried to download it as well and it still isn't working.

**Comment by scottgonzalez** [comment]
I took the time to manually edit the Vader theme to something that's more usable and will actually download. Try [this](http://jqueryui.com/download/#!zThemeParams=5d000001001d06000000000000003d8888d844329a8dfe02723de3e5701258a13d5ba490adca99e4a02bf259c3083bccd292fbc7a815b30f470ff7864f8c0d0abbfd0926063d26d115eb0a5af33202d9000fc77557b5eaadab27b95343b6afc2055fea7893986242328d3d52c33e42a1bac039c773403a2fc422b5f290442a8cd0a072767b3f55c3afcb623b351f68ca2b6633da9ef5c1ccaff4e3e68407056d214525f521c599c357af8f3aa68b4922e17210a73b0c9d9b26dc4e59024dc8994cdebbf1619990c4cc353a2cc62c03cc07ccd2324befaedfc5e10d3cd3c6137a3fca3787b560ed1ae15dd3a56b287f406e859f339f08a1de837a22a0a8c2ee679c9b63308a1d920e2e0e56ff7fc9f14a1cea9ac0580f875b3618be7123252314c9d458d4199702c36ff2e9835bb0e04ebae6a67d725a68ce62d49e8431e8f22394d284d34ad09e3773888e9280758eba2b2c0e14fb6309ac690520f03dc3ad075cedc43715ca617d29c42135f4d701f268bc55c2af641738f30afe9b782f9b7719cc23c87afeeef5492dac179cb359d3aac14948c74fa51a50083f2dd34428e29313ef4aa1458d66217486d3d271e893ded32579fcbdd3471fe69eb6dc4b2d0282070db0265785bd3ed5fd7804b72d2624d0210979490aa9a45ad4544feeeb93b13dd7ffc4c3119c) and let me know if you still have problems.

**Comment by NaheemAdio** [comment]
Still isn't working. Below is a screenshot of the web page when i try to download it.

![screen shot 2017-01-13 at 10 54 13 pm](https://cloud.githubusercontent.com/assets/23334344/21952165/5587abc2-d9e3-11e6-822a-e5d2bb50f90b.png)

**Comment by miguelangelss4** [comment]
Still being down :(

**Comment by scottgonzalez** [comment]
I'm not sure how else to help then. That link is still working fine for me.

**Comment by miguelangelss4** [comment]
The error is not surfing on http://jqueryui.com/download, but when you scroll down and select "Vader" theme and click on download, you have the error.

**Comment by scottgonzalez** [comment]
And I said to use the link I provided instead. Did you try that?

**Comment by miguelangelss4** [comment]
sorry, y didn't see that message.

**Comment by scottgonzalez** [comment]
Can anyone respond as to whether the link I provided worked for them?

**Comment by fnagel** [comment]
Link provided by @scottgonzales works for me, but when using the theme select at http://download.jqueryui.com/download it chrashes. Using Chrome 55 on Win10.

**Comment by miguelangelss4** [comment]
scott your link redirects to jquery default download page. Maybe your work had expired, 16 days ago it worked.

**Comment by scottgonzalez** [comment]
Download builder URLs don't expire, as long as the selected version is still available. You should end up on the download page. The question is whether you get the right theme when you click the download button.

**Comment by alibby251** [comment]
I've tried downloading the same Vader file from the download page today, using the link provided by @scottgonzalez, and by choosing "Vader"manually from the download page. It's throwing a "site can't be reached' error in Chrome 56 and FF Developer Edition on Win 8 on both occasions. Others seem to download OK.

**Comment by scottgonzalez** [comment]
DO NOT CLICK ON THE VADER THEME. The link I provided has an edited theme that you should be using.

**Comment by scottgonzalez** [comment]
This should now work in production. Please let me know if you still have trouble with the Vader theme.

**Comment by fnagel** [comment]
@scottgonzalez Works for me now (link and select on page)!
