### ISSUE TITLE
Quick Access is gone

### ISSUE THREAD

**Issue by CyberPsych1996** [jquery/download.jqueryui.com#339]
Hello what happened with the quick access that used to be in the end of the page?

**Comment by scottgonzalez** [comment]
They're at the top of http://jqueryui.com/download/, where they have always been.

**Comment by CyberPsych1996** [comment]
it is not at the button where it says books there used to be a quick acces and other that says books

**Comment by scottgonzalez** [comment]
Well, that's been gone for three years, and is not related to this repo.
