### ISSUE TITLE
Cannot read property 'fadeIn' of undefined

### ISSUE THREAD

**Issue by ibookhotel** [jquery/download.jqueryui.com#341]
Having issue with jQuery UI Date picker 1.11.4.
When integrate within word press theme named Centum.
All other themes works well.
http://test1.greendotcreations.com/jquery-ui-datepicker/
The picker is initialised but the error occurred when i try to open date picker atached to input component.
I am not sure is that a bug, but it worth checking out.

Uncaught TypeError: Cannot read property 'fadeIn' of undefined
    at HTMLInputElement._showDatepicker (datepicker.min.js?ver=1.11.4:11)
    at HTMLInputElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLInputElement.r.handle (jquery.js?ver=1.12.4:3)

It is interfering with jQuery effects library http://test1.greendotcreations.com/wp-content/themes/Centum/js/effects.js.

If i remove effects.js, date picker works well. So it is conflict.
Is it possible to force picker to open in this situation?

**Comment by scottgonzalez** [comment]
This is the bug tracker for the download builder, not jQuery UI itself. Please file a bug at https://bugs.jqueryui.com/newticket and make sure to link to a reduced test case using jsbin or jsFiddle. We will not debug code on a hosted site using WordPress.
