### ISSUE TITLE
SELECTMENU

### ISSUE THREAD

**Issue by cyntechtic** [jquery/download.jqueryui.com#342]
Please do note that the select menu does not scroll with windows page neither does it have a scroll bar to view the entire list of menu items. That is a select menu with a large list of items can not be scrolled to view the lower list of the menu item, see sample below
![capture2](https://cloud.githubusercontent.com/assets/6288225/23106051/1a052788-f6e8-11e6-8013-eace0c31fc1d.JPG)
see below for sample of side scroll bar for a select menu item
![capture3](https://cloud.githubusercontent.com/assets/6288225/23106098/a94d9cae-f6e8-11e6-949b-2432d5f2c08a.JPG)

![capture](https://cloud.githubusercontent.com/assets/6288225/23105930/aab6afce-f6e6-11e6-84b1-c83327df3d3a.JPG)

**Comment by scottgonzalez** [comment]
This is the bug tracker for the download builder, not for jQuery UI itself. The correct bug tracker is https://bugs.jqueryui.com; however, using both IE and Edge on http://jqueryui.com/selectmenu/, I see scrollbars for "Select a number"
