### ISSUE TITLE
ThemeRoller: Clickable Default State and Icon do not generate any css

### ISSUE THREAD

**Issue by revinhart** [jquery/download.jqueryui.com#344]
In the theme roller, I can specify Icon for Clickable Default State.
However, when I click "generate" button, the css is missing this line:

This statement is missing for version 1.12.1

.ui-state-default .ui-icon {
	background-image: url("images/ui-icons_e0d5d5_256x240.png");
}

However for version 1.11.4, the above statement exists.

NOTE:
I have submitted this issue before. See #335.

**Comment by scottgonzalez** [comment]
As noted in the other issue you submitted, this has been fixed in the jquery-ui repo. You will need to wait for the next release before the fix will be visible in production.
