### ISSUE TITLE
Support spaces instead of tabs in ThemeRoller

### ISSUE THREAD

**Issue by GSPP** [jquery/download.jqueryui.com#347]
(Migrating issue https://bugs.jqueryui.com/ticket/15173 since I posted to the wrong bugtracker.)

It would be useful to configure 4 spaces instead of tabs. Our project uses spaces. I believe that years ago jQuery UI used spaces as well. So far we avoided the big source control change to change the whitespace. This necessitates a manual fixup after download unfortunately. It would be convenient if ThemeRoller supported such an option.

**Comment by scottgonzalez** [comment]
You shouldn't be linting third party code.
