### ISSUE TITLE
Don't set font-family: inherit in ThemeRoller (set no font at all)

### ISSUE THREAD

**Issue by GSPP** [jquery/download.jqueryui.com#349]
Don't set `font-family: inherit;` because this rule can actually cause a change in `font-family` for buttons that are inside a widget such as tabs. Then, `inherit` applies the inherited `font-family` (likely inherited from html or body) whereas using no `font-family` rule at all applies the user agent style for the button! In other words the `font-family: inherit;` rule causes an unintended change and it seems to not be good for anyhing specific.

It would make sense to have a ThemeRoller feature that makes it possible to not generate any font declaration at all. Maybe the special string `unset` could be used for this in the UI. Due to lack of browser support ThemeRoller must then omit the `font-family` rule as opposed to emitting `font-family: unset;`.

**Comment by scottgonzalez** [comment]
This is not something we could easily implement. ThemeRoller uses a simple template system that just does token replacement. ThemeRoller itself has no control over the stylesheet templates that are provided, and the templating system wouldn't allow for the source (jQuery UI) to provide a stylesheet that would allow the entire rule to be removed.

While we could do a lot of refactoring to make this possible, it's not worth the effort. You can simply modify your theme as needed.

**Comment by GSPP** [comment]
Makes sense. Thanks for responding.
