### ISSUE TITLE
1.8.24

### ISSUE THREAD

**Issue by valenpo** [jquery/download.jqueryui.com#351]
Can't download custom theme for 1.8.24. Is it possible to do that?

**Comment by scottgonzalez** [comment]
No, that hasn't been supported for over four years.

**Comment by valenpo** [comment]
Thanks! Is it available less, scss scheme for 1.8.24? Or is it possible to make build service using gulp?

**Comment by scottgonzalez** [comment]
Nope

**Comment by valenpo** [comment]
@scottgonzalez thanks!
