### ISSUE TITLE
JQuery themeroller won't allow download of theme

### ISSUE THREAD

**Issue by DavidGraper** [jquery/download.jqueryui.com#352]
Simple as that -- clicking the "Download Theme" button after designing a theme doesn't do anything.

Is a server filled somewhere?

Thanks.  - Dave

**Comment by scottgonzalez** [comment]
It does do something. It takes you to the download page where you have to click another download button after choosing the components and an optional CSS scope.

**Comment by DavidGraper** [comment]
Scott:  Very sorry -- I should have tried it on another computer -- my Mac on Ethernet has no problems at all, my PC on Wifi was a different story.   I tried to delete the thread.

Thanks -- and sorry again.  - Dave
