### ISSUE TITLE
DatePicker Icon Not displaying

### ISSUE THREAD

**Issue by tweetoxygen** [jquery/download.jqueryui.com#353]
Hello,
After modifying the UI theme, it shows exactly as I want in the preview panel but when I download it and add the css and JS file to my html file, I notice that everything seems to be Ok except for the datePicker icons (Previous and Next). They no longer appear by default and when I mouse over, a background shows without the icon showing. 
This is the result I am trying to achieve. 
![resu](https://user-images.githubusercontent.com/9431878/28776201-821b8496-75ed-11e7-9b55-0de8b6cbaea9.JPG)

This is what I get. 
![get](https://user-images.githubusercontent.com/9431878/28776276-e3106992-75ed-11e7-908f-a262b25f6ecb.JPG)

Any way I can get to fix this?

**Comment by scottgonzalez** [comment]
Does it look correct in the index file included in the download?

**Comment by tweetoxygen** [comment]
Hello Scott,

Yes it does show correctly on the index file. Just when I add the CSS and the JS file to my HTML page, then the icons no longer show..

**Comment by scottgonzalez** [comment]
If it works properly in the index file, then it sounds like something in your page is overriding the styles.

**Comment by tweetoxygen** [comment]
Funny enough  I thought of that but then, I removed all the other tags in my page and left only the text box for the datepicker and still same.

**Comment by tweetoxygen** [comment]
Here is all my code for the calendar

<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>jQuery UI Datepicker - Select a Date Range</title>
  <link rel="stylesheet" href="jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css"> 
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="jquery-ui.js"></script>

</head>
<body>

<style>
	body { 
		font-family: verdana; 
		font-size: 12px; 
		margin: 30px;
	}	
</style>
 
<label for="from">From</label>
<input type="text" id="from" name="from" placeholder="Departure Date..." />
<label for="to">to</label>
<input type="text" id="to" name="to" placeholder="Return Date..."/>
 


<script>
  $(function() {
    $( "#from" ).datepicker({
      minDate:0,
      onSelect: function( selectedDate ) {
        $( "#to" ).datepicker( "option", "minDate", selectedDate );
      }
    });
    $( "#to" ).datepicker({      
      minDate:0,
      onSelect: function( selectedDate ) {
        $( "#from" ).datepicker( "option", "maxDate", selectedDate );
      }
    });
  });
</script>

</body>
</html>
