### ISSUE TITLE
Download button ThemeRoller greyed out

### ISSUE THREAD

**Issue by draai080** [jquery/download.jqueryui.com#354]
Yesterday I have used the Themeroller on Jquery.com for the first time to create an customized Theme. This worked fine. Later that day I decided to use the tool again for one additional adjustments. Now I encounter the issue that when I make the first change in the base template the Download button is greyed out. When I refresh the page my changes are still visible and the button is not longer greyed out, but it is not active. Klicking on it has no effect.

So I'm not able to make an customized Theme at the moment. What can be the cause of this? Thanks in Advance.

**Comment by volkflo** [comment]
Same problem here with this [link](http://jqueryui.com/themeroller/?scope=&folderName=custom-theme&bgImgOpacityError=95&bgImgOpacityHighlight=55&bgImgOpacityActive=65&bgImgOpacityHover=75&bgImgOpacityDefault=75&bgImgOpacityContent=75&bgImgOpacityHeader=75&cornerRadiusShadow=8px&offsetLeftShadow=-8px&offsetTopShadow=-8px&thicknessShadow=8px&opacityShadow=30&bgImgOpacityShadow=0&bgTextureShadow=flat&bgColorShadow=%23aaaaaa&opacityOverlay=30&bgImgOpacityOverlay=0&bgTextureOverlay=flat&bgColorOverlay=%23aaaaaa&iconColorError=%23cd0a0a&fcError=%23cd0a0a&borderColorError=%23cd0a0a&bgTextureError=flat&bgColorError=%23fef1ec&iconColorHighlight=%232e83ff&fcHighlight=%23363636&borderColorHighlight=%23fcefa1&bgTextureHighlight=flat&bgColorHighlight=%23fbf9ee&iconColorActive=%23454545&fcActive=%23ffffff&borderColorActive=%235c8a39&bgTextureActive=flat&bgColorActive=%23689c40&iconColorHover=%23454545&fcHover=%23fff&borderColorHover=%232695cc&bgTextureHover=flat&bgColorHover=%232695cc&iconColorDefault=%23215968&fcDefault=%23fff&borderColorDefault=%23033249&bgTextureDefault=flat&bgColorDefault=%2306618e&iconColorContent=%23222222&fcContent=2222&borderColorContent=%23aaaaaa&bgTextureContent=flat&bgColorContent=%23ffffff&iconColorHeader=%23215968&fcHeader=%23215968&borderColorHeader=%23aaaaaa&bgTextureHeader=highlight_soft&bgColorHeader=%23cccccc&cornerRadius=4px&fwDefault=normal&fsDefault=1.1em&ffDefault=DINMittelEF-Regular%2Ccalibri%2Carial%2Chelvetica)

You are not able to download the custom theme if you change some of the values.

**Comment by shellig** [comment]
Same issue

**Comment by mgol** [comment]
Does this work now? See https://github.com/jquery/download.jqueryui.com/issues/390#issuecomment-706430874

**Comment by mgol** [comment]
Closing per my above comment.
