### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by PanderMusubi** [jquery/download.jqueryui.com#356]
Please, fix broken links on the website found by W3C's link checker:

https://validator.w3.org/checklink?uri=http%3A%2F%2Fdownload.jqueryui.com%2F&hide_type=all&recursive=on&depth=&check=Check

**Comment by Krinkle** [comment]
On <https://jqueryui.com/download/>, all visible links exist according to W3C Link Checker. There was 1 error about invisible metadata association not working (<https://jqueryui.com/wp-json/>) but that's not important.

For <https://jqueryui.com/themeroller/>, similarly all visible links work. Perhaps there were more errors in 2018, but it looks good now.
