### ISSUE TITLE
ThemeRoller: Generate file containing variables for use in SASS/LESS

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/download.jqueryui.com#36]
I think a YAML file of all the variables set in a Themeroller CSS file would be enough. we can build a compass plugin that takes a YAML file and convert it into constants that SASS can use. I think this is probably the same with LESS too.

Themeroller is too awesome to not have its variables made usable in other parts of a site's design! Keep up the good work folks!

http://bugs.jqueryui.com/ticket/5902

**Comment by 4Digits** [comment]
+1 for SASS / SCSS support
