### ISSUE TITLE
Can't download from JQUERYUI

### ISSUE THREAD

**Issue by shababahmad786** [jquery/download.jqueryui.com#365]
When trying to download I get a Host Error.
![image](https://user-images.githubusercontent.com/34052394/64842778-a0665480-d61c-11e9-9b7e-48c9c645c20b.png)

**Comment by yonder83** [comment]
I noticed same issue. Download page is broken.

**Comment by sabyasachimondal** [comment]
I am also facing the same issue. Any clue, when the issue will be resolved.

**Comment by milanvorel** [comment]
It has been reported 2 weeks ago:
https://github.com/jquery/download.jqueryui.com/issues/359
Developers jqueryUI are not involved anymore.

**Comment by mrpryce** [comment]
hi am having problem downloading jquery UI its showing a bad gateway is there another link to get this library

**Comment by studioekinox** [comment]
Same Issue, cloudflare error....

**Comment by donprecious** [comment]
is their any other way to download

**Comment by shababahmad786** [comment]
Hi guys, I found the working files and i am sharing these files
[jquery-ui-files.zip](https://github.com/jquery/download.jqueryui.com/files/3624618/jquery-ui-files.zip)

**Comment by shababahmad786** [comment]
https://github.com/shababahmad786/Jquery-Ui-Files.git
It's link for downloading ui files

**Comment by lukasbableck** [comment]
You can use my download server to build jqueryUI.

http://templersmc.net:8888/download
