### ISSUE TITLE
Unable to Download Custom JQuery UI

### ISSUE THREAD

**Issue by sjmaklari** [jquery/download.jqueryui.com#366]
Unable to download JQuery UI using custom package builder selecting:

Selected "Draggable" (dependencies were auto-selected)
Selected "Dialog" (dependencies were auto-selected)

Clicking download results in a Bad Gateway 502 error page.

Error 502 Ray ID: 51747d289c04719b • 2019-09-16 17:16:34 UTC
Bad gateway

**Comment by Jekeam** [comment]
A similar problem with any attempt to download

**Comment by dmattsson** [comment]
Same for me, I'm located in Stockholm

**Comment by bci24** [comment]
same porblem here...

**Comment by ImSketch** [comment]
Same problem!

**Comment by ChiHam-Lee** [comment]
Same ..

**Comment by lukasbableck** [comment]
You can use my download server to build jqueryUI.

http://templersmc.net:8888/download

**Comment by dabasti** [comment]
Same here

**Comment by ImSketch** [comment]
> 
> 
> You can use my download server to build jqueryUI.
> 
> http://templersmc.net:8888/download

Is down

**Comment by lukasbableck** [comment]
https://jqueryui.templersmc.net/download

**Comment by neatnate** [comment]
Same here!
