### ISSUE TITLE
CAN'T DOWNLOAD JQUERY UI!!!

### ISSUE THREAD

**Issue by avirupdutta** [jquery/download.jqueryui.com#367]
Error 502 Ray ID: 518466a62b06dc8d • 2019-09-18 15:37:25 UTC
Bad gateway

**Comment by lukasbableck** [comment]
You can use my download server to build jqueryUI.

https://jqueryui.templersmc.net/download

**Comment by AL-X-dev** [comment]
Me too -- can't download.

**Comment by txsilva** [comment]
Error 502 Ray ID: 518ca78f6fb3e074 • 2019-09-19 15:39:49 UTC
Bad gateway

**Comment by avirupdutta** [comment]
**Until the developers resolve the bug use this fully Working CDN by Google**
[https://developers.google.com/speed/libraries/#jquery-ui](url)
