### ISSUE TITLE
jQuery UI - Error 502

### ISSUE THREAD

**Issue by MC-dvega** [jquery/download.jqueryui.com#368]
Error 502 - Bad Gateway

![ss_240919_14](https://user-images.githubusercontent.com/48128770/65552520-785ad900-ded9-11e9-8d88-3dd621784a56.png)

**Comment by clintdowning** [comment]
Still getting this error.

**Comment by Exkauige** [comment]
Here's a workaround if you know the version:

https://code.jquery.com/ui/1.12.1/jquery-ui.min.js

**Comment by clintdowning** [comment]
> Here's a workaround if you know the version:
> 
> https://code.jquery.com/ui/1.12.1/jquery-ui.min.js

Thank you!

**Comment by lukasbableck** [comment]
If you want you can also use my download server https://jqueryui.templersmc.net/download to build your custom jQueryUI.

**Comment by igor-tv** [comment]
> If you want you can also use my download server https://jqueryui.templersmc.net/download to build your custom jQueryUI.
This site is down.

**Comment by lukasbableck** [comment]
It’s not down for me, probably a short outage.
