### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by suzyq275** [jquery/download.jqueryui.com#369]
"... uses Cloudflare's Always Online™ technology" but it is offline?
Is this something that will be fixed? 
Does anyone know?
![image](https://user-images.githubusercontent.com/39744923/65640385-dce86780-dfaf-11e9-8b85-4f4bbf7ed715.png)

**Comment by lukasbableck** [comment]
It's been like that since almost a month.

If you want you can use my download server https://jqueryui.templersmc.net/download to build  jQueryUI.

**Comment by efann** [comment]
Thank you. Your server clone works great.
