### ISSUE TITLE
Unable to download jQuery UI

### ISSUE THREAD

**Issue by nicklese** [jquery/download.jqueryui.com#371]
I've been getting a bad gateway error all night. Is there an idea
<img width="952" alt="Screen Shot 2019-10-01 at 11 08 27 AM" src="https://user-images.githubusercontent.com/1158541/65984006-fff59a00-e43b-11e9-97f9-7e1529935b00.png">
 when It will be resolved?

**Comment by damien-ylopo** [comment]
Also getting this error the last 2 days.

**Comment by okan3358** [comment]
Still getting this error

**Comment by karolkarnowski** [comment]
Someone will fix this or you give a sh** ?

**Comment by lukasbableck** [comment]
You can use my download server, it doesn’t seem like someone will fix the official one.

https://jqueryui.templersmc.net/download

**Comment by karolkarnowski** [comment]
Thanks man :)
