### ISSUE TITLE
error download

### ISSUE THREAD

**Issue by dwikydiasl** [jquery/download.jqueryui.com#372]

**Comment by clami219** [comment]
There is an error in download.jqueryui.com when trying to download a custom version (meaning only some of the components) of JQuery UI.
An error is shown by Cloudflare. Here a screenshot:
![Screenshot_2019-10-03 download jqueryui com 502 Bad gateway](https://user-images.githubusercontent.com/6358909/66111833-f9952880-e5c9-11e9-97b3-74dfc35176d1.png)

**Comment by ignacioscl** [comment]
the error is still happening, how could download custom versions?

**Comment by lukasbableck** [comment]
You can use my download server to build custom versions.

https://jqueryui.templersmc.net/
