### ISSUE TITLE
Download broken

### ISSUE THREAD

**Issue by KenHull** [jquery/download.jqueryui.com#376]
Not really new but I can see no answer.  Trying to download autocomplete files from jqueryui

Error 502 Ray ID: 520eccb8bb6315ea • 2019-10-05 10:44:20 UTC
Bad gateway

**Comment by MajorTennis** [comment]
Still the case.

**Comment by Tea56** [comment]
still the case here too

**Comment by atlasjon** [comment]
Still busted.

**Comment by timhj** [comment]
still busted :(

**Comment by timhj** [comment]
https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-532583043
