### ISSUE TITLE
Builder fails to download (Cloudflare 502)

### ISSUE THREAD

**Issue by arieWolck** [jquery/download.jqueryui.com#377]

**Comment by Skatox** [comment]
Same here

**Comment by michaeldisaro** [comment]
Up

**Comment by Riaz1** [comment]
Error 502 Ray ID: 522973ffded5564f • 2019-10-08 16:22:21 UTC
Bad gateway

**Comment by NoLE** [comment]
error....

**Comment by timhj** [comment]
Same here

**Comment by timhj** [comment]
New download link hosted by a gh user 
https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-532583043
