### ISSUE TITLE
ThemeRoller not updating

### ISSUE THREAD

**Issue by BeanyTheSane** [jquery/download.jqueryui.com#378]
I can view the default and several themes but if I change anything it reverts to a plain state and refuses to update for anything after that.

**Comment by ginsingtome** [comment]
I get exactly the same thing.

**Comment by NcMichel** [comment]
same here.

**Comment by honsberg** [comment]
can someone fix this?

**Comment by honsberg** [comment]
you can use this themeroller: https://jqueryui.templersmc.net/themeroller

**Comment by NcMichel** [comment]
thanks for the job, it seems to work.

**Comment by fnagel** [comment]
Duplicate of #359
