### ISSUE TITLE
Downloads links are broken

### ISSUE THREAD

**Issue by talley** [jquery/download.jqueryui.com#379]
Try to download and  see it by yourself.I got this

Error 502 Ray ID: 523056c7ba5b3898 • 2019-10-09 12:25:44 UTC
Bad gateway

**Comment by elwray** [comment]
The same for me.

**Comment by ssicet** [comment]
Same here

**Comment by josuemy** [comment]
Same here

**Comment by serzhmir** [comment]
Same here

**Comment by flons** [comment]
Yup, broken for me too :(

**Comment by antoiba86** [comment]
Broken for me too.

**Comment by postonoh** [comment]
Same here

**Comment by adelbs** [comment]
While the link is broken... an alternative:
https://jqueryui.com/download/all/

**Comment by scarhead7** [comment]
It's broken for me as well.

**Comment by ginsingtome** [comment]
Broken for me too.

**Comment by cytsai1008** [comment]
me too

**Comment by ItzelRendon** [comment]
Same here

**Comment by haight6716** [comment]
Ray ID: 52751e9feb36c99d • 2019-10-17 20:46:02 UTC
