### ISSUE TITLE
502 Error on JQuery UI Download Link

### ISSUE THREAD

**Issue by dvisotsky** [jquery/download.jqueryui.com#383]
I am unable to download any JQuery UI packages/themes.
Ray ID: 525d9e1d8998e3b6 • 2019-10-15 00:18:46 UTC

**Comment by bobojoga** [comment]
Same here.
Ray ID: 52600895bab69127 • 2019-10-15 07:20:58 UTC

**Comment by hirsch-b** [comment]
Same here:
Ray ID: 526933faae00bd91 • 2019-10-16 10:03:27 UTC

**Comment by acflint** [comment]
+1 here
Error 502 Ray ID: 526c3f5f8f8cbc78 • 2019-10-16 18:55:31 UTC

**Comment by mskvorcovs** [comment]
Error 502 Ray ID: 5270e3fa9d79c442 • 2019-10-17 08:26:57 UTC

**Comment by avolpe98** [comment]
Error 502 Ray ID: 52724b33ed96be0a • 2019-10-17 12:32:10 UTC

**Comment by avolpe98** [comment]
Please solve it fast, I need to download for work

**Comment by avolpe98** [comment]
Ok thanks a lot

**Comment by enricobarretta** [comment]
> I don't think the official server will be fixed. But you can use mine!
> https://jqueryui.templersmc.net

Thank you so much. You're Awesome!

**Comment by enricobarretta** [comment]
Thank you!!

**Comment by honsberg** [comment]
> 
> 
> I don't think the official server will be fixed. But you can use mine!
> https://jqueryui.templersmc.net

can you pls push your changes to this repository? 

why is the official server never be updated?

**Comment by avolpe98** [comment]
honsber look here: https://github.com/jquery/download.jqueryui.com/issues/390
