### ISSUE TITLE
Unable to download, Please Check for Server Errors.

### ISSUE THREAD

**Issue by biswabijaya** [jquery/download.jqueryui.com#386]
![Screenshot 2019-10-20 at 4 52 36 AM](https://user-images.githubusercontent.com/22062430/67152512-82fc6880-f2f5-11e9-88ab-28c327d0dc8b.png)

**Comment by avolpe98** [comment]
Here the solution:
https://github.com/jquery/download.jqueryui.com/issues/383

before create an issue check if someone else solved your problem yet
