### ISSUE TITLE
Issue downloading version 1.12.1 "Theme"

### ISSUE THREAD

**Issue by Godlesshawk** [jquery/download.jqueryui.com#395]
Hey guys,

I can't download the new Version of "jQueryUI" with individual Theme. 
Could someone please help me?
That's the download link:
[https://jqueryui.com/](https://jqueryui.com/download/#!zThemeParams=5d00000100ff05000000000000003d8888d844329a8dfe02723de3e5701fa198449035fc0613ff729a37dd818cf92b1f6938fefa90282d04ae436bb72367f5909357c629e832248af2c086db4ab730aa4cced933a88449eca62a2077f3b23d47f58a712d809b6088edfb376d83e455b59f1bd990b3e590e5b9859f221228f742dd665bf96b9fd9e3574ac7fcf6b14180770cff19badfcd5912cafe1d15076a7cd5d6a38f5bf3de8777b7e0e46ddecad664f6da67d9e7ed6866f388de5f52cfa28800fa5f71b0d93ac44a679f85e674f50a8fa0d7091eeb89e4b61afc078b70df935316b54fef3ee3f350018f888afd65b83b1aa11577cf937c215bae2e5e55588ceb579c861c19667fd1f186603329813b27af2c7c673689add67c71bf05955878df03b921ede3f895c3b23aae7b86cbed8d3539e6d6795e69a7a8bd94c049208eee6cbbb88bfeb0788988037dc3bebccc889d34b1e89d03011a2a1425c09711378a2058c9cf79a3022dbcffa63f0366c7b5a4d1e2da0c3cb70ec0dc311bd10631b737a9a797d68640f31c416006647304297a0f4758bd7050d8a76bab2d414c6fc2f8d7459e9019c4d41e3b79c78e456703f8cba0ac01c1adae86d23ccdecda8afe23c7a77ab25dce84e6e7d76a4a0067190a03cfd31b17f2ef41b9769f7e28adef1ec42c8ede8f443143d6ffbcc2bd3el)

**Comment by Godlesshawk** [comment]
Hey guys,

since today I am getting the "ERROR 502".
Please help :).
Thank you

**Comment by Chewbacca222222** [comment]
@Godlesshawk same here unfortunately, have you found a mirror anywhere?

**Comment by Godlesshawk** [comment]
@Chewbacca222222 nope not yet, but if you find one - please inform me.

**Comment by Godlesshawk** [comment]
@Chewbacca222222  it works again. :)
