### ISSUE TITLE
Error downloading builder

### ISSUE THREAD

**Issue by kelvinwl** [jquery/download.jqueryui.com#396]
Hello.
Just now I had an issue trying to download the builder at https://jqueryui.com/download/

**Date**: 2019-11-07 
**Time**: 12:40:00 UTC

**Version**: 1.12.1(Stable, for jQuery1.7+)
**Components**: All

**Comment by kelvinwl** [comment]
After I click download I am redirected to the CloudFlare CDN showing HTTP Error 502 (Bad gateway)

**Comment by fnagel** [comment]
Duplicate of #359
