### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by metalox** [jquery/download.jqueryui.com#399]
Unable to download Ray ID: 53939085ea0dc29a • 2019-11-21 15:05:55 UTC

**Comment by david-fanin** [comment]
Me too !

Error 504 Ray ID: 53ba887b0d5dee89 • 2019-11-26 08:36:10 UTC Gateway time-out

**Comment by Mostafa-Yusuf** [comment]
Me too !

Error 504

**Comment by duy4fun** [comment]
Ray ID: 53c4e0caab62d96e • 2019-11-27 14:44:05 UTC

**Comment by cosmonoid** [comment]
Same here: Ray ID: 53cb1188d972d721 • 2019-11-28 08:45:56 UTC

**Comment by daniel-ilan** [comment]
same here. Ray ID: 5468a4dd89156aad • 2019-12-17 11:44:15 UTC

whats up with this? this is going on for weeks...

**Comment by fnagel** [comment]
Duplicate of #359
