### ISSUE TITLE
ERROR 502 BADGATEWAY

### ISSUE THREAD

**Issue by MindPower99** [jquery/download.jqueryui.com#400]
ERROR 502 BADGATEWAY

**Comment by femke77** [comment]
Still happening today.

**Comment by ryanlaws** [comment]
Still happening.

**Comment by tomvanlier** [comment]
And still happening

**Comment by WulleBulle** [comment]
Error 502 Ray ID: 540ebc42e9a67cfa • 2019-12-06 13:51:35 UTC
Bad gateway

Nearly everyday. What's happening to Github since it was annected by MS? It gets worser.....

**Comment by xobrooklynn** [comment]
I keep having the same issue as well.

**Comment by radioman-00** [comment]
still cannot download

**Comment by fnagel** [comment]
Duplicate of #359
