### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by ldguazo** [jquery/download.jqueryui.com#404]
![image](https://user-images.githubusercontent.com/44182341/71285494-5257a000-2333-11ea-91e1-8708ebf49e52.png)

**Comment by ldguazo** [comment]
Thanks for the fix!

**Comment by kaleshkk** [comment]
The issue still exists
![Screenshot from 2019-12-21 12-52-26](https://user-images.githubusercontent.com/34179843/71304800-37e3fc00-23f1-11ea-8755-0e2125aa6020.png)

**Comment by ldguazo** [comment]
Yesterday i was able to download JQuery-UI whitout problems, it is still?

**Comment by ldguazo** [comment]
i think it's already fixed

![image](https://user-images.githubusercontent.com/44182341/71312292-0706c580-23f7-11ea-99a2-e6014623e894.png)
