### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by maxime-lucas** [jquery/download.jqueryui.com#406]
Hi,
When I try to download a custom jquery built version, I got this error when I click on the Download button.
For your information, the section "Theme" seems to be broken too.

**Comment by JacobCN** [comment]
Error 502 Ray ID: 54db0c760be9ebb5 • 2019-12-31 08:57:55 UTC
Bad gateway

**Comment by andymitchell79** [comment]
I'm experiencing the same as of 6:45 am 1/2/2020

**Comment by pcollaog** [comment]
Same error

 Error 502 Ray ID: 54ef91399b8ccfb3 • 2020-01-02 20:43:48 UTC

**Comment by fnagel** [comment]
Duplicate of #359
