### ISSUE TITLE
Error502

### ISSUE THREAD

**Issue by KancerEzeroglu** [jquery/download.jqueryui.com#409]
Hi, When I try to download jquery 1.12, I had a problem.

![image](https://user-images.githubusercontent.com/1583507/71969858-cf29bb80-3207-11ea-9c35-2edcc1ce6be3.png)

Could you check the problem?

Thanks in advance

**Comment by nlguy516** [comment]
Same here. Just now, January 13, 2020. Has the issue persisted the entire week or is it recurring?

**Comment by shelbyinloes** [comment]
I am also having this error. 1/14/2020

**Comment by vasilevich** [comment]
I don't remember the last time it even worked...

**Comment by i-wizard** [comment]
you can get it using this link  https://jqueryui.com/download/all/

**Comment by wsug** [comment]
I also encountered this problem showing 502

**Comment by fnagel** [comment]
Duplicate of #359
