### ISSUE TITLE
Download builder not working

### ISSUE THREAD

**Issue by bergschold** [jquery/download.jqueryui.com#414]
I When I click the download button I get an error page

**Comment by ashleefoureyes** [comment]
Confirming the above. Get Bad Gateway error (502). Seems to be on and off - will work for a few minutes and then reset to default and users will be unable to edit or download.

**Comment by mr-stivo** [comment]
Same problem. Cannot choose a theme and clicking download gives Bad Gateway error (502).

**Comment by fnagel** [comment]
Duplicate of #359
