### ISSUE TITLE
 jqueryui -download problem

### ISSUE THREAD

**Issue by mohamadali93** [jquery/download.jqueryui.com#430]
I can't download the jqueryui

**Comment by DependencyHell** [comment]
Try a stable version : https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

**Comment by obwang827** [comment]
thankyou
Error 502 Ray ID: 576c683e2b7ea354 • 2020-03-20 03:39:39 UTC
Bad gateway
Is still happening

**Comment by DependencyHell** [comment]
Yes, they will not fix it soon with the custom downloader, see this post :

https://github.com/jquery/download.jqueryui.com/issues/390

The only way is to build the project on your side to use the downloader...

**Comment by fnagel** [comment]
Duplicate of #359
