### ISSUE TITLE
Download Builder gives error 502

### ISSUE THREAD

**Issue by IfeOlulesi** [jquery/download.jqueryui.com#438]

**Comment by PaulBoundy** [comment]
Hi Gurus.
Can this be brought to the attention of someone that can enable the download of the jQueryUI builder.
Thanks

![image](https://user-images.githubusercontent.com/40392215/79060469-7d8c4380-7cc4-11ea-88eb-617b949f7661.png)

**Comment by airplanenoise** [comment]
+1

**Comment by goozak** [comment]
See [Issue Thread Regarding the 502 Error #390](https://github.com/jquery/download.jqueryui.com/issues/390)

**Comment by nikki2002** [comment]
unable to download. 502 error

**Comment by withoutyou0919** [comment]
+1

**Comment by fnagel** [comment]
Duplicate of #359
