### ISSUE TITLE
Error 502 Bad Gateway

### ISSUE THREAD

**Issue by dhiyazaidi** [jquery/download.jqueryui.com#443]
Browser and Cloudfire(Auckland) are working but, Host is error (download.jqueryui.com).

**Comment by Xites** [comment]
Same here
Error 502 Ray ID: 5876e1b9b9b9dbe7 • 2020-04-21 11:49:26 UTC
Bad gateway

**Comment by LuisAlcocer** [comment]
I had the same problem, but I used the next address and finally got the file:
https://jqueryui.com/download/all/

**Comment by fnagel** [comment]
Duplicate of #359
