### ISSUE TITLE
Error 502 Ray ID: 58a9f8e3ff128afc • 2020-04-27 16:38:09 UTC Bad gateway

### ISSUE THREAD

**Issue by LittleSmileSun** [jquery/download.jqueryui.com#445]
I can't download custom components.

**Comment by mwxgaf** [comment]
its my problem too
![jqui](https://user-images.githubusercontent.com/39344217/80400017-6d34b500-88cf-11ea-9dc5-1f9960b70e4e.png)

**Comment by mdmower** [comment]
Duplicate of https://github.com/jquery/download.jqueryui.com/issues/444

**Comment by mwxgaf** [comment]
I want to download a special theme

**Comment by joandersonalves** [comment]
Erro 502, não consigo fazer download!!

**Comment by fnagel** [comment]
Duplicate of #359
