### ISSUE TITLE
1.12.1(Stable, for jQuery1.7+) dowload problem.

### ISSUE THREAD

**Issue by an80x86** [jquery/download.jqueryui.com#446]
1.12.1(Stable, for jQuery1.7+) dowload problem.

**Comment by dyslexicanaboko** [comment]
I have the same problem. Been trying since last night. I just keep getting Bad gateway error which is happening on the download.jqueryui.com side.

**Comment by mirasoldavila13** [comment]
same

**Comment by fnagel** [comment]
Duplicate of #359
