### ISSUE TITLE
I can't downloads builder jQuery UI

### ISSUE THREAD

**Issue by NeerapaTongtitram** [jquery/download.jqueryui.com#452]
[When I asked to load it. Will have a problem Error 502 Bad gateway](url)

**Comment by peca11** [comment]
Same here

**Comment by The-Bright-Lord** [comment]
Bumping this

**Comment by mevsme** [comment]
bump

**Comment by nanuit** [comment]
bump

**Comment by andersjarl** [comment]
bump

**Comment by Erseni** [comment]
bump

**Comment by Kirnos** [comment]
bump

**Comment by anhaabaete** [comment]
Same Here!

**Comment by anhaabaete** [comment]
Error 502 Ray ID: 58f4a616ed49f5ff • 2020-05-06 18:08:49 UTC

**Comment by syl666** [comment]
Same

**Comment by syl666** [comment]
Can anyone recommend an alternative?

**Comment by benadzs** [comment]
Hi! You can use this:
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>

**Comment by The-Bright-Lord** [comment]
Anyone wanting this can download the individual files from the releases zip from

https://github.com/jquery/jquery-ui/releases/tag/1.12.1

You can then use what you want

**Comment by syl666** [comment]
Thank YEWS!

**Comment by MrD0llaro** [comment]
The ThemeRoller not working too

**Comment by psme222** [comment]
same

**Comment by ToniSHernandez** [comment]
Same here and it is annoying as I have a project due by next week...

**Comment by faizy7sheikh** [comment]
I can not download

**Comment by amots** [comment]
same -  failed to download

**Comment by kaggabba** [comment]
same problem

**Comment by Dtue** [comment]
Same to me!

**Comment by OrunbekK** [comment]
Same problem to me, please help

**Comment by Robert-Watts** [comment]
Same for me

**Comment by coros-sanborn** [comment]
Any progress on this?

**Comment by andrewjohnstrong** [comment]
bump

**Comment by hismightiness** [comment]
Ugh.

**Comment by der-rote-hund** [comment]
Same. Bad gateway…

**Comment by rustykowski** [comment]
The jQuery UI project seems to be abandoned. Latest commit 3 years ago. We all have do look for alternatives …

**Comment by fnagel** [comment]
Duplicate of #359
