### ISSUE TITLE
Can't download customized version

### ISSUE THREAD

**Issue by Zempheroth** [jquery/download.jqueryui.com#454]
Select required components in builder, click Download - Cloudflare 
got 
![image](https://user-images.githubusercontent.com/5180270/81788558-6337c680-950b-11ea-87df-d4effce420fd.png)

**Comment by XavLal** [comment]
Hi, same issue !

**Comment by sebastianbustos** [comment]
Same...

**Comment by radioman-00** [comment]
same issue on 14-5-2020

**Comment by SIMSON20** [comment]
Hi! same issue...

**Comment by PatriotDevOps** [comment]
Same issue blocking some work

**Comment by brendan8c** [comment]
I also can not download.
Same problem.

**Comment by fnagel** [comment]
Duplicate of #359
