### ISSUE TITLE
Download Builder not work

### ISSUE THREAD

**Issue by kefywk** [jquery/download.jqueryui.com#457]
This is the error Error 502 Ray ID: 594e8c34da27d618 • 2020-05-17 15:59:48 UTC
Bad gateway

https://download.jqueryui.com/download

**Comment by mijiapps** [comment]
Same.

**Comment by tgrahn2** [comment]
same

**Comment by spacemanjan** [comment]
same

**Comment by mijiapps** [comment]
I built the project locally and was able to generate a custom build. This is probably the best solution for now.

**Comment by d-signet** [comment]
Not always possible.

Project does not build on windows machines, for example

 Unsupported platform for modern-syslog@1.1.2: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by Tiahin** [comment]
Please remove `npm-shrinkwrap.json` and try `npm i -f`

**Comment by fnagel** [comment]
Duplicate of #359
