### ISSUE TITLE
Tried to download just Tabs, got a 500 something error

### ISSUE THREAD

**Issue by GerryOnGithub** [jquery/download.jqueryui.com#482]
I see a lot of other download problem reports, you guys gots a problem

**Comment by bpospanov** [comment]
same

**Comment by MortenAndersen** [comment]
Exactly the same for me

**Comment by themikmas** [comment]
Same here

**Comment by bpospanov** [comment]
found it here boys. it works
http://dir.by/developer/jquery_ui/download/

**Comment by fumelolz** [comment]
same

**Comment by Globerada** [comment]
+1

**Comment by showkatalisalim** [comment]
Get it from here: 
https://drive.google.com/drive/folders/13SGHQ1SfUjchvusyT-XUNiKyzwQAjHac?usp=sharing
