### ISSUE TITLE
Unable to download autocomplete widget

### ISSUE THREAD

**Issue by prashantc-bits** [jquery/download.jqueryui.com#484]
Error 502 Ray ID: 59fc93fadb7ede29 • 2020-06-07 18:53:49 UTC
Bad gateway

**Comment by showkatalisalim** [comment]
Get it from here (everything included): 
https://drive.google.com/drive/folders/13SGHQ1SfUjchvusyT-XUNiKyzwQAjHac?usp=sharing

**Comment by EndermanAPM** [comment]
This doesn't solve the problem if you only want to load the autocomplete plugin.

**Comment by prashantc-bits** [comment]
i have resolved it on own...... Downloaded microsoft.jquery.unobtusive.ajax library from nuget package manager and reference the required file in views wherein you want your partial views to appear.

It is evident now that for MVC partial views with @Ajax.ActionLink() to work, we are supposed to use Microsoft.Jquery.Unobrusive.Ajax library from nuget.

**Comment by showkatalisalim** [comment]
@EndermanAPM  I'm not sure you indicated me. But guessing it was me, I would like to inform you that "autocomplete" is included inside the "jquery-ui.js" file. and it's starting line number is 5587.  if you want only "autocomplete" plugin, then copy the wizard codes and paste into a new file giving it a name and use it.
