### ISSUE TITLE
 1.12.1 (Stable, for jQuery1.7+)

### ISSUE THREAD

**Issue by musarra** [jquery/download.jqueryui.com#487]
can't build apk with buildozer for android and kivy....need matplotlib backend, see issue below

 Downloading matplotlib from https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip

urllib.error.HTTPError: HTTP Error 403: Forbidden
Download failed retrying in a second...Download failed retrying in a second...Download failed retrying in a second...Download failed retrying in a second..
command failed

**Comment by fnagel** [comment]
Download static files should still work. Just tried the above link and was able to download the zip without issues.

**Comment by zoldos** [comment]
> can't build apk with buildozer for android and kivy....need matplotlib backend, see issue below
> 
> Downloading matplotlib from https://jqueryui.com/resources/download/jquery-ui-1.12.1.zip
> 
> urllib.error.HTTPError: HTTP Error 403: Forbidden
> Download failed retrying in a second...Download failed retrying in a second...Download failed retrying in a second...Download failed retrying in a second..
> command failed

I was able to download it via your link, but the files are all dated 9/14/2016. Is this the newest version??

**Comment by mgol** [comment]
Yes, that's still the newest version.
