### ISSUE TITLE
Error 502- Download broken

### ISSUE THREAD

**Issue by virmix** [jquery/download.jqueryui.com#488]
Error 502 Ray ID: 5a2c24c68d3dff58 • 2020-06-13 13:26:30 UTC
Bad gateway

https://download.jqueryui.com/download

**Comment by skolsen1** [comment]
Getting the same thing.

**Comment by Lajull** [comment]
Broken for me too :/

**Comment by Mbotes** [comment]
its broken, both for custom a complete package download

**Comment by getangar** [comment]
Same behavior for me.

**Comment by LeLampadaire** [comment]
Same thing...

**Comment by sarojupa** [comment]
Still getting 502

**Comment by synfinatic** [comment]
+1

**Comment by Osempu** [comment]
Broken link! :(

**Comment by scott-fisher-iii** [comment]
Same here

**Comment by jtsSTECH** [comment]
same.

**Comment by allanemerson** [comment]
Same. It's been this way for a while.

**Comment by nageshraoj** [comment]
Getting same error. It looks like it has been for while. Any solution? 
![Capture](https://user-images.githubusercontent.com/19434056/85100979-053f8280-b21f-11ea-9e44-852fad76b348.JPG)

**Comment by magicsunday** [comment]
Try https://jqueryui.templersmc.net/download#!version=1.12.1&components=110000010001000001100000110010000000000000000000

**Comment by nageshraoj** [comment]
@magicsunday Thank you so much. It is working for me.

**Comment by kasunvp** [comment]
Still get a 502 from https://download.jqueryui.com/.

**Comment by bpospanov** [comment]
https://jqueryui.templersmc.net/download/#!

**Comment by fnagel** [comment]
Duplicate of #359
