### ISSUE TITLE
can't download jqueryui/themeroller

### ISSUE THREAD

**Issue by Offori** [jquery/download.jqueryui.com#489]
Error 502 Ray ID: 5a467a734d74de29 • 2020-06-16 18:08:50 UTC
Bad gateway

**Comment by jtsSTECH** [comment]
Same issue.

**Comment by ScottFarrell** [comment]
Same issue.

**Comment by Black2developerBR** [comment]
Yes, I have the same error.

**Comment by prostoAE** [comment]
Same issue.

**Comment by Offori** [comment]
If you find any solution, please let me know

**Comment by Offori** [comment]
don't really get you please can you be more clear?

**Comment by sd-design** [comment]
Same error - Error 502 Ray ID: 5a53f0e2ee360000 • 2020-06-18 09:21:35 UTC

**Comment by RobGvk** [comment]
Same issue, come guys WHEN will this be fixed!!!

**Comment by organicon** [comment]
Indeed.  Suffering from the same error.  
Seems like a pretty critical bug.

**Comment by SPdowns** [comment]
I'm getting bad gateway

**Comment by bpospanov** [comment]
https://jqueryui.templersmc.net/download/#!

**Comment by SPdowns** [comment]
That link worked for me. Thank you @bpospanov

**Comment by fnagel** [comment]
Duplicate of #359
