### ISSUE TITLE
502:Bad Gateway

### ISSUE THREAD

**Issue by felixfreidman** [jquery/download.jqueryui.com#491]
Hello everyone, tried to download the JQueryUI, but the request returned 502 error. I tried several times with several browsers, but still didn't get what I wanted.
Thanks!

**Comment by CARAXSoftware** [comment]
Same Issue on my side! 502 Error from "download.jqueryui.com".

**Comment by stefan-popescu** [comment]
Same here, it no longer works since at least 2 weeks. :(

**Comment by captcurrent** [comment]
Well add me to the list.   frustrating

**Comment by tei187** [comment]
Sadly, same issue. Stops at cloudflare, host turns out an error for download.jqueryui.com

**Comment by bpospanov** [comment]
https://jqueryui.templersmc.net/download/#!

**Comment by stefan-popescu** [comment]
Awesome, thanks bpospanov!

**Comment by captcurrent** [comment]
Might be a little off topic..... I was hoping this would generate a .js file.....I am not quite sure how to use resulting package

**Comment by bpospanov** [comment]
> Might be a little off topic..... I was hoping this would generate a .js file.....I am not quite sure how to use resulting package

there will be plenty files. put all of them into your project and add jquery-ui.min.css and jquery-ui.min.js and include them into your template

**Comment by fnagel** [comment]
Duplicate of #359
