### ISSUE TITLE
[jQuery UI] Error 502 in Download Builder

### ISSUE THREAD

**Issue by ziaratban** [jquery/download.jqueryui.com#495]
i can not download custom jquery ui.

**Result :**
![image](https://user-images.githubusercontent.com/6462878/86022952-45350f80-ba40-11ea-9c44-7f8972719066.png)

________________________________________________________________

**Query :**
![image](https://user-images.githubusercontent.com/6462878/86022890-33ec0300-ba40-11ea-85d1-12d8aac03b36.png)

**Comment by kanixask** [comment]
Yes i'm having the same issue

**Comment by fnagel** [comment]
Duplicate of #359
