### ISSUE TITLE
Error 502 when download 

### ISSUE THREAD

**Issue by dhuynh08t4** [jquery/download.jqueryui.com#500]
After select some options. then click download, Error 502 display
Here is my link 
https://jqueryui.com/download/#!version=1.12.1&components=111111111110111100000000010000001000100000000001

https://download.jqueryui.com/download
![image](https://user-images.githubusercontent.com/60699975/86593218-031b4900-bfbf-11ea-8fdd-3d0531727157.png)

**Comment by recoverjp** [comment]
Same mistake here.

**Comment by recoverjp** [comment]
Use https://jqueryui.templersmc.net/

**Comment by ocsross96** [comment]
Also have this issue, using @recoverjp's suggestion above

**Comment by RangoSn** [comment]
Thanks @recoverjp

**Comment by fnagel** [comment]
Duplicate of #359
