### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by hectordufau** [jquery/download.jqueryui.com#501]
Error 502 Ray ID: 5af218354a68f607 • 2020-07-07 14:00:56 UTC
Bad gateway

**Comment by RangoSn** [comment]
Use https://jqueryui.templersmc.net/

**Comment by RangoSn** [comment]
Try to download a stable version, I think the problem is when we try to download a custom version.
It work for me.

**Comment by fnagel** [comment]
Duplicate of #359
