### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by mgjovero-github** [jquery/download.jqueryui.com#502]
Error 502 Ray ID: 5af8bc89f9660a98 • 2020-07-08 09:21:42 UTC
Bad gateway

**Comment by RangoSn** [comment]
Use this dude https://jqueryui.templersmc.net/

**Comment by mgjovero-github** [comment]
Thanks much 😊.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RangoSn** [comment]
Try to download a stable version, I think the problem is when we try to download a custom version.
It work for me.

**Comment by fnagel** [comment]
Duplicate of #359
