### ISSUE TITLE
Error 502 

### ISSUE THREAD

**Issue by lemospace** [jquery/download.jqueryui.com#508]
Bad gateway

Can't download and can't select themes

**Comment by ruud-kok** [comment]
I also get a 502 error, when downloading from here: https://jqueryui.com/download/#!version=1.12.1&components=100000010000000000000000010010000000000000000000

**Comment by endyknov** [comment]
I can't dowload too. Please fix.

**Comment by LasyCoder** [comment]
i can't  download too. it shows 502 error

**Comment by AssassinGT** [comment]
Error 502:host error. Even with vpn .it's not accessible.

**Comment by fnagel** [comment]
Duplicate of #359
