### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by robbfoster** [jquery/download.jqueryui.com#511]
Error 502 Ray ID: 5b2c92a2ec36f0f6 • 2020-07-14 16:20:44 UTC
Bad gateway

**Comment by AlechkoStudio** [comment]
Second day the same issue

**Comment by Lorena-Vallejos** [comment]
Error 502 Ray ID: 5b33eb861fa8baa2 • 2020-07-15 13:44:46 UTC
Bad gateway

**Comment by exphoenee** [comment]
Error 502 Ray ID: 5b3543f3fdfcd40f • 2020-07-15 17:39:53 UTC
Bad gateway

**Comment by robbfoster** [comment]
Here's a work around that I found HTH
https://jqueryui.com/download/all/

**Comment by AlechkoStudio** [comment]
@robbfoster Thank you, but i need a custom package :(
Error 502 Ray ID: 5b360c584ddacab4 • 2020-07-15 19:56:41 UTC

**Comment by rweigel** [comment]
Use https://jqueryui.templersmc.net/

**Comment by AlechkoStudio** [comment]
Thank you @rweigel

**Comment by fnagel** [comment]
Duplicate of #359
