### ISSUE TITLE
Download Builder gives Error 502

### ISSUE THREAD

**Issue by rafaraca** [jquery/download.jqueryui.com#513]
Tried to download and got the download page : https://jqueryui.com/download/
Clicked the download button and then got a :
Error 502 Ray ID: 5b6024ef7f6c09c8 • 2020-07-20 22:33:31 UTC
Bad gateway

Some help, please?

**Comment by atstockland** [comment]
At the top of the download page, click on the quick link for "Stable"

**Comment by fnagel** [comment]
Duplicate of #359
