### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by vosidiy** [jquery/download.jqueryui.com#517]
![image](https://user-images.githubusercontent.com/36692987/88478490-3ddf2400-cf62-11ea-8801-16adcf545595.png)

**Comment by sagrael** [comment]
Error 502 Ray ID: 5b960e693e24dfa5 • 2020-07-27 11:35:19 UTC
Bad gateway

**Comment by ddison** [comment]
Same issue (Cloudflare for me was Chicago) but I get the Host error trying to download any version of theme.

**Comment by fnagel** [comment]
Duplicate of #359
