### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by lalandeepak** [jquery/download.jqueryui.com#520]
I want to download but getting HOST error. Please provide me a genuine links.
Thanks
Deepak
deepaklalankumar@gmail.com

**Comment by RobertDickey** [comment]
This is still happening 8 hours later.

**Comment by zachakbar** [comment]
Still happening for me

**Comment by matrentman** [comment]
Still happening, someone please fix.

**Comment by topmonroe9** [comment]
Still not able to download

**Comment by fnagel** [comment]
Duplicate of #359
