### ISSUE TITLE
 Jquery ui download builder is broken

### ISSUE THREAD

**Issue by ErnestoPaz** [jquery/download.jqueryui.com#527]
I am wondering if the jquery ui download builder is broken.
I have used it many times before, but now it doesn't seem to be working.

I untick all the stuff I click the button at the bottom marked download and sent me to this link https://download.jqueryui.com/download and the page shows and error message.

**Comment by ABlack990** [comment]
#390 looks like it's been an issue for a while.  Not sure when it's going to be fixed, but this thread has a response a ways down that offers a solution

**Comment by quitequinn** [comment]
https://jqueryui.templersmc.net/download/

**Comment by fnagel** [comment]
Duplicate of #359
