### ISSUE TITLE
download doesn't work Aug 2020

### ISSUE THREAD

**Issue by vadzvnik** [jquery/download.jqueryui.com#528]
![image](https://user-images.githubusercontent.com/3526487/89710605-3a786f00-d94a-11ea-904b-44c44f289177.png)

**Comment by Nighteyez07** [comment]
As of Aug 10th 2020, 3:15 PST this issue is still happening

**Comment by Sicos1977** [comment]
I got the same today

**Comment by AnomalyInc-Pete** [comment]
Still happening at 11m GMT.

**Comment by awtkeithlin** [comment]
Still happening

**Comment by Iteracy** [comment]
Same issue.

**Comment by nyneplus** [comment]
I hope it will be fixed soon, i need to update now...

**Comment by reinejohansson** [comment]
Same here:
![image](https://user-images.githubusercontent.com/798272/89900723-6747b300-dbe4-11ea-98ed-e778b75ba4b1.png)

**Comment by reinejohansson** [comment]
Same here
![image](https://user-images.githubusercontent.com/798272/89900953-ad047b80-dbe4-11ea-9480-4028bcb3282a.png)

**Comment by liam1908** [comment]
Same issue here. I hope it will be fixed soon

**Comment by fnagel** [comment]
Duplicate of #359

Please see here: https://github.com/jquery/download.jqueryui.com/issues/359#issuecomment-672286486
