### ISSUE TITLE
Error 502 bad gateway

### ISSUE THREAD

**Issue by zakstark** [jquery/download.jqueryui.com#530]
Hi there, I'm getting an Error 502 bad gateway when trying to use... https://jqueryui.com/download/
....no matter what widgets I choose to download.

**Comment by all-your-base** [comment]
I can confirm, the download link doesn't work; it shows a Cloudflare error page.

**Comment by leckman** [comment]
also experiencing this problem

**Comment by winglovecola** [comment]
Hello also receive this error. Please look into it. Thanks

**Comment by AuctionArmsCEO** [comment]
Error 502 at https://download.jqueryui.com/download - Doesn't matter what configuration is attempted.

**Comment by mfhassan22** [comment]
i am also getting 502 error

**Comment by anastasia-son** [comment]
I have the same issue - Error 502

**Comment by TensorTom** [comment]
same

**Comment by mran3** [comment]
same

**Comment by demirmusa** [comment]
same

**Comment by Vic40k** [comment]
same

**Comment by ShahManali99** [comment]
> Hi there, I'm getting an Error 502 bad gateway when trying to use... https://jqueryui.com/download/
> ....no matter what widgets I choose to download.

Facing same issue

**Comment by tekdru** [comment]
I'm having the same problem when trying to download a custom package.

**Comment by schmelik** [comment]
bump

**Comment by leckman** [comment]
You can use this mirror to download: https://github.com/jquery/download.jqueryui.com/issues/384#issuecomment-621833464

**Comment by tekdru** [comment]
Thank you!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ShahManali99** [comment]
> You can use this mirror to download: [#384 (comment)](https://github.com/jquery/download.jqueryui.com/issues/384#issuecomment-621833464)

Thank you :)

**Comment by fnagel** [comment]
Duplicate of #359
