### ISSUE TITLE
> You can use my download server to build jqueryUI.

### ISSUE THREAD

**Issue by KPTousey** [jquery/download.jqueryui.com#534]
> You can use my download server to build jqueryUI.
> 
> https://jqueryui.templersmc.net/download

502 Bad Gateway

_Originally posted by @StefanoAI in https://github.com/jquery/download.jqueryui.com/issues/360#issuecomment-533860665_

I get a server down error when attempting this connection.
8/27/20pm.

**Comment by fnagel** [comment]
Duplicate of #359
