### ISSUE TITLE
Gateway error

### ISSUE THREAD

**Issue by flo-rider** [jquery/download.jqueryui.com#536]
This URL throws a gateway error when clicking download: https://jqueryui.com/download/#!version=1.12.1&components=000000010000000000000010000000000000000000000000

**Comment by zoldos** [comment]
Yup, I'm getting it too on Firefox and Opera and again when I turned my VPN off. :(

**Comment by sebastian-alfers** [comment]
👍

**Comment by mpalladinru** [comment]
Are you ever going to fix this? It's not working for more than day. No any VPN works.

**Comment by JeanCaEscalante** [comment]
This URL throws a gateway error when clicking download: https://jqueryui.com/download/#!version=1.12.1&components=110000010001000000100000100000000000000000000000

**Comment by mattyonice** [comment]
Facing same issue. Tried to access with Chrome.

**Comment by tiyberius** [comment]
Same here. I assumed it was because I was trying to download from New Zealand, but glad to know that other people are having issues too

**Comment by whiplashoo** [comment]
Same issue here, 502 gateway error.

**Comment by richard-edgecreative** [comment]
I have tried yesterday and today (2nd August 2020) and getting the same error.

**Comment by Lueton** [comment]
same here

**Comment by bartmelton** [comment]
ditto

**Comment by fnagel** [comment]
Duplicate of #359
