### ISSUE TITLE
Error 502

### ISSUE THREAD

**Issue by Heartmanx** [jquery/download.jqueryui.com#538]
I couldn't download jqueryui, what can I do to download it

**Comment by amanjainIIITB** [comment]
It's still down

**Comment by davecameos** [comment]
Same issue. It is still down

**Comment by choisuill** [comment]
same issue.....   :(

**Comment by choisuill** [comment]
https://jqueryui.com/download/all/
what about here?

**Comment by choisuill** [comment]
I don't know if this will help

**Comment by ibrahimgarba** [comment]
I cant download it.

**Comment by amarg26** [comment]
Jquery team can you please resolve it asap ?

**Comment by fnagel** [comment]
Duplicate of #359
