### ISSUE TITLE
Error 502 Bad gateway

### ISSUE THREAD

**Issue by AribSheikh** [jquery/download.jqueryui.com#541]
Ray ID: 5cea1b695bbb14dd • 2020-09-06 18:03:30 UTC
Can't download JQuery ui

**Comment by BychkovVV** [comment]
I have this problem too.
Thank you in advance!

**Comment by khaledmostafaismaiel** [comment]
me too

**Comment by Cirunz** [comment]
Same here

**Comment by luismigil** [comment]
same here

**Comment by Jahnavi-21** [comment]
Same Here

**Comment by Gofer01** [comment]
So everyone is having the same problem. So who on the jQuery team is assigned to fix the download issue?

**Comment by fnagel** [comment]
Duplicate of #359
