### ISSUE TITLE
impossible to download jQueryUI from site Error 502

### ISSUE THREAD

**Issue by maxcann76** [jquery/download.jqueryui.com#543]
1- from: https://jqueryui.com/download/ I click download button
2- I receive: Error 502 Ray ID: 5d08271a1bfd6f64 • 2020-09-10 09:34:22 UTC
Bad gateway

**Comment by Corcules** [comment]
Same

**Comment by eriksaetren** [comment]
Same :( Sad panda

**Comment by wert90** [comment]
maybe this link help you

https://jqueryui.com/download/all/

**Comment by fnagel** [comment]
Duplicate of #359
