### ISSUE TITLE
Downloadsection on jqueryui.com has a Bad Gateway Error

### ISSUE THREAD

**Issue by Ben-bittec** [jquery/download.jqueryui.com#545]
[Bildschirmvideo aufnehmen 2020-09-14 um 15.50.43.zip](https://github.com/jquery/download.jqueryui.com/files/5218851/Bildschirmvideo.aufnehmen.2020-09-14.um.15.50.43.zip)

**Comment by fnagel** [comment]
Duplicate of #359
