### ISSUE TITLE
 Error 502

### ISSUE THREAD

**Issue by torrhenStark666** [jquery/download.jqueryui.com#549]
In the builder when selecting the desired items and clicking on the download button, the error occurs, more than a week since this occurred.

**Comment by zensabbah** [comment]
Same stuff dude! How to solve? I remember the same error even month ago!

**Comment by ipsmile** [comment]
Error 502 Ray ID: 5d8648bd5ca1e50e • 2020-09-25 16:57:25 UTC
Bad gateway

Issue still persists.

**Comment by fnagel** [comment]
Duplicate of #359
