### ISSUE TITLE
Getting 502 error

### ISSUE THREAD

**Issue by mr-lfph** [jquery/download.jqueryui.com#550]
Getting 502 error while i tried to download jquery ui datepicker 

![jdp](https://user-images.githubusercontent.com/61219914/94355937-5b904d00-00bb-11eb-9b97-b128b0082345.JPG)

**Comment by ALIHAIDER15** [comment]
facing same issue

**Comment by DarkCellar** [comment]
Same here.

**Comment by fabricioct** [comment]
Also with me

**Comment by Glave** [comment]
same as me

**Comment by gillesvrstrtn** [comment]
same ...!

**Comment by pbson** [comment]
same here

**Comment by CipherLab** [comment]
Yup... anyone have the datepicker only they'd care to share?

**Comment by ald0acuna** [comment]
Same!!

**Comment by Eli-Pan** [comment]
Trying to download the theme. Same issue here.

**Comment by m2rivero** [comment]
same

**Comment by aal4all** [comment]
here also

**Comment by LeopoldoDeLaLlave** [comment]
same

**Comment by fnagel** [comment]
Duplicate of #359
