### ISSUE TITLE
502 error from Kiev or any VPN

### ISSUE THREAD

**Issue by Venegrad** [jquery/download.jqueryui.com#553]
![image](https://user-images.githubusercontent.com/9676703/95201250-52ecf480-07e8-11eb-97dc-4eb716a50fc7.png)

**Comment by Venegrad** [comment]
withot vpn error too

**Comment by bkindig** [comment]
I'm getting this also with and without a VPN across all browsers.

**Comment by Venegrad** [comment]
i think jquery is not supported in 2020, site and support is not working. 
Forums say this error has been hanging for 2 years...

**Comment by mgol** [comment]
See #390.
