### ISSUE TITLE
502 error ...

### ISSUE THREAD

**Issue by floydianslip** [jquery/download.jqueryui.com#554]
... when using Download Builder

**Comment by bkindig** [comment]
I am also getting this issue.

**Comment by jomiquel** [comment]
Getting the same issue when using Bownload Builder, that build this link:
https://jqueryui.com/download/#!version=1.12.1&components=101000010100100000000010011010000000000000000000

**Comment by wizzicollo** [comment]
Hi, I am getting also a 502 bad gateway

**Comment by mgol** [comment]
See #390.
