### ISSUE TITLE
Download builder returns 521 on attempted download

### ISSUE THREAD

**Issue by DannyZB** [jquery/download.jqueryui.com#557]
Returns a "Server Down" error. Makes it unusable.
When is this fixed?

**Comment by jotadeaa** [comment]
This is the error shown:
> Error 521 Ray ID: 5e4a84aafdc608d9 • 2020-10-19 12:31:49 UTC
> Web server is down

**Comment by mjpvz** [comment]
I'm getting the same issue

**Comment by fvmartynov** [comment]
Also getting the same issue.

**Comment by gpashis** [comment]
I am also getting the same issue.

**Comment by mgol** [comment]
We're looking into it. See #390.

**Comment by gpashis** [comment]
@mgol #390 is being there since a year ago. Any hope that it will be back to normal soon?

**Comment by mohammadTaghy** [comment]
I am also getting the same issue.

**Comment by mgol** [comment]
> @mgol #390 is being there since a year ago. Any hope that it will be back to normal soon?

I think the issue reported in #390 originally has been fixed, the 502 error no longer happens and on the download builder host I see the server is running. The issue with the 521 error now occurred in a different place and we're investigating it right now.

**Comment by redplant0** [comment]
I'm having the same issue.

**Comment by mgol** [comment]
Can you all check again? We think we have a fix for that.

**Comment by gpashis** [comment]
Wow! it's back again. This is really a great.
@mgol Thanks a lot for quick response.

**Comment by Marfyy** [comment]
Working again. Thanks for quick response.

**Comment by jotadeaa** [comment]
It's working now. Thanks a lot.

**Comment by AntsHere** [comment]
The file jquery-ui.min.js contains "undefined" instead of code.

**Comment by fnagel** [comment]
@AntsHere Take a look here: https://github.com/jquery/download.jqueryui.com/issues/390

**Comment by mgol** [comment]
The 521 issue is gone, closing.
