### ISSUE TITLE
Custom download has empty minified js file

### ISSUE THREAD

**Issue by arbuthnott** [jquery/download.jqueryui.com#559]
I just tried to download a custom build for 1.12.1. It included all **Core**, all **Interactions** and the **Mouse** widget. I used the downloaded jquery-ui.js as a linked script and it worked as expected. However, the downloaded jquery-ui.min.js file was empty - it only included the comment header and the single word `undefined`, haha.

Of course I could generate the min file in other ways, just letting you know as a courtesy.

**Comment by fnagel** [comment]
Take a look here: #390

**Comment by mgol** [comment]
Let's track the minified issue here, #390 got a bit too big.

The conversation about the issue started here: https://github.com/jquery/download.jqueryui.com/issues/390#issuecomment-712896182

**Comment by fnagel** [comment]
> Seems like all downloads for version 1.12.1 have only undefined in the minified file. Downloads for version 1.11.4 and lower work without issues.

My findings from https://github.com/jquery/download.jqueryui.com/issues/390#issuecomment-712950764

**Comment by TheGP** [comment]
15 days, really? jquery-ui.min.js has undefined instead of js script

**Comment by mgol** [comment]
@TheGP If you want something done quicker, the best way is to submit a PR.

**Comment by mgol** [comment]
This should be fixed now.
