### ISSUE TITLE
Not able to download jquery ui from the official site.

### ISSUE THREAD

**Issue by shailendra33** [jquery/download.jqueryui.com#570]
Not able to download jquery ui from the official site.

**Comment by mgol** [comment]
Please post more details. What exactly happens, what are the steps to reproduce, etc. we can’t do anything with just “it doesn’t work”.

**Comment by shailendra33** [comment]
If you click to download, it never downloads.

**Comment by shailendra33** [comment]
yes , this is a persistent issue probably for last one year. Steps taken so far:
1) I go to the url :  https://jqueryui.com/download/
2) No matter what options you choose, OR do not any choose any option and click on Download.
3)It shows as if, it has started downloading, but never downloads, not even 1 bit and remains like this for ever.
I was using firefox, then i tested on google chrome, but one and the same result in both the browser.
I tested even today after reading your message, still today it is not working.
My all other downloads work smoothly.
God knows what is the issue.

**Comment by klonos** [comment]
I can also confirm that I am able to download w/o any issue. @shailendra33 perhaps try a different browser, or try temporarily disabling any antivirus software? 🤷🏼

**Comment by javedpulok** [comment]
NOTE: I tried to download from the official site with chrome browser as a result failed but with Microsoft edge download successfully. try different browser

**Comment by oldhelps** [comment]
I clicked the "DOWNLOAD" button,but I cant download!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fnagel** [comment]
@oldhelps This issue should be solved since at least a year or something. Can you give some more info on the error?

**Comment by fnagel** [comment]
Closed due to lack of activity. Please reopen if needed!
