### ISSUE TITLE
Wrong version displayed or wrong content being returned for AutoComplete

### ISSUE THREAD

**Issue by Jojoshua** [jquery/download.jqueryui.com#585]
1. Go to the download site (v1.13.0 is default selected)
2. Click Toggle All to turn everything off
3. Only select AutoComplete and Download
4. View the jquery-ui.min.js file and the header shows jQuery UI - v1.12.1...  instead of 1.13.0

**Comment by Krinkle** [comment]
I'm unable to reproduce this. The default erison is now v1.13.2, and using Steps 2-4 above, all of the file header in the downloaded zip reflect `1.13.2`, not `1.12.1` or any other version. Please leave a comment or file a new issue if you still experience this problem.
