### ISSUE TITLE
Attempting to download customized theme

### ISSUE THREAD

**Issue by Mark-Boyce** [jquery/download.jqueryui.com#602]
After making a few customizations, attempting to download the theme results in a 404 error and the customizations are not downloaded.

**Comment by mueslinibbles** [comment]
Likewise, getting the same problem.
Customise the theme then goto the download page and get a 'service unavailable' error
![Screenshot 2023-11-06 164804](https://github.com/jquery/download.jqueryui.com/assets/145599949/f4e45ad4-5761-4bf2-94cd-6d279e801883)

**Comment by mgol** [comment]
@mueslinibbles @Mark-Boyce is the behavior reproducible? Does it happen all the time or periodically? Can you lay out very, very precise steps to reproduce? Exactly which URL you visit, what you click/type, step by step.

I need this as just if I try to change a few things, I can download the themed package without issues.

**Comment by mueslinibbles** [comment]
Yes, this is happening every time I try to download either the base theme, or a customisation of it.
Simplest, repeatable, route to the error is;
1. Goto https://jqueryui.com/
2. Click 'Themes' from menu
3. Goto the 'Gallery' tab of the ThemeRoller.
4. Select the Base theme.
5. Click the download button.
6. The Download Builder window appears, then after a moment the 'service unavailable' 404 error box appears.

hope this helps.

**Comment by mgol** [comment]
Thank you! I can reproduce it now.

From what I see, there's a request triggered to [https://download.jqueryui.com/download/theme?themeParams=ffDefault%3D...](https://download.jqueryui.com/download/theme?themeParams=ffDefault%3DArial%252CHelvetica%252Csans-serif%26fsDefault%3D1em%26fwDefault%3Dnormal%26cornerRadius%3D3px%26bgColorHeader%3De9e9e9%26bgTextureHeader%3Dnone%26borderColorHeader%3Ddddddd%26fcHeader%3D333333%26iconColorHeader%3D444444%26bgColorContent%3Dffffff%26bgTextureContent%3Dnone%26borderColorContent%3Ddddddd%26fcContent%3D333333%26iconColorContent%3D444444%26bgColorDefault%3Df6f6f6%26bgTextureDefault%3Dnone%26borderColorDefault%3Dc5c5c5%26fcDefault%3D454545%26iconColorDefault%3D777777%26bgColorHover%3Dededed%26bgTextureHover%3Dnone%26borderColorHover%3Dcccccc%26fcHover%3D2b2b2b%26iconColorHover%3D555555%26bgColorActive%3D007fff%26bgTextureActive%3Dnone%26borderColorActive%3D003eff%26fcActive%3Dffffff%26iconColorActive%3Dffffff%26bgColorHighlight%3Dfffa90%26bgTextureHighlight%3Dnone%26borderColorHighlight%3Ddad55e%26fcHighlight%3D777620%26iconColorHighlight%3D777620%26bgColorError%3Dfddfdf%26bgTextureError%3Dnone%26borderColorError%3Df1a899%26fcError%3D5f3f3f%26iconColorError%3Dcc0000%26bgColorOverlay%3Daaaaaa%26bgTextureOverlay%3Dnone%26bgImgOpacityOverlay%3D0%26opacityOverlay%3D30%26bgColorShadow%3Ddddddd%26bgTextureShadow%3Dflat%26bgImgOpacityShadow%3D0%26opacityShadow%3D30%26thicknessShadow%3D5px%26offsetTopShadow%3D0px%26offsetLeftShadow%3D0px%26cornerRadiusShadow%3D8px&callback=jQuery37105136947468357909_1699310539350&_=1699310539351) and that results in a 500 with the following stack trace:

```
Error: No dimensions set for texture "none"
    at ThemeRoller._textureUrl (/app/lib/themeroller.js:270:10)
    at new ThemeRoller (/app/lib/themeroller.js:160:29)
    at Frontend.theme (/app/download.js:195:20)
    at /app/server.js:97:35
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at /app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)
```

**Comment by mgol** [comment]
A workaround for now is to avoid clicking "Download" on a theme but instead to click "Edit" and then "Download theme".
