### ISSUE TITLE
"Download style" button on ThemeRoller

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#97]
The 2nd top custom-component download is "No components", aka theme only.

Knowing we have a significant amount of users behaving that way, perhaps it would be useful having a button on ThemeRoller allowing them to do so, it would save their time.

**Comment by Krinkle** [comment]
We have a "Toggle All" box that can be disabled, which appears to create a theme-only build. Given we're in maintenance mode, I think that's good enough. Patch welcome though.
